/**
 * @module AppRegistry
 * @description Unified registry of all myUNO micro-apps / service entry points.
 *
 * This is the SINGLE canonical inventory. Other layers (VERTICAL_GROUPS,
 * Navigator CLUSTERS, quickActionsCatalog, AllAppsDrawer) derive their data
 * from here instead of maintaining independent lists.
 *
 * Convention:
 *   - `id` is unique across the entire registry.
 *   - `verticalId` links to VERTICALS[x].id when the service maps to a DB vertical.
 *   - `groupId` maps to VERTICAL_GROUPS (Discover "All Services").
 *   - `clusterIds` maps to Navigator journey clusters.
 *   - `status` controls visibility: 'active' is live, 'soon' is greyed-out.
 */

import { APP_ROUTES } from '@/lib/config/routes';
import { ECOSYSTEM_APP_TRIPLET } from '@/lib/ecosystemGlossary';

export type AppGroupId =
  // Journey-based groups (current canonical)
  | 'arrive'
  | 'live'
  | 'enjoy'
  | 'health'
  | 'settle'
  | 'invest'
  | 'maintain'
  | 'help'
  // Legacy / internal groups (kept for backward compat)
  | 'home'
  | 'transport'
  | 'leisure'
  | 'wellness'
  | 'admin_docs'
  | 'maintenance'
  | 'manage'
  | 'build'
  | 'lifestyle'
  | 'b2b'
  | 'internal';

export type NavigatorClusterId =
  | 'arrive'
  | 'live'
  | 'legal'
  | 'invest'
  | 'manage'
  | 'build'
  | 'enjoy'
  | 'family';

export type AppStatus = 'active' | 'soon' | 'pro';

export interface AppEntry {
  id: string;
  route: string;
  verticalId?: string;
  groupId: AppGroupId;
  clusterIds: NavigatorClusterId[];
  labelEn: string;
  labelRu: string;
  labelTh: string;
  icon: string;
  status: AppStatus;
  /** User personas that should see this in quick actions (empty = none) */
  personaTags: string[];
  bookable: boolean;
}

export const APP_REGISTRY: Record<string, AppEntry> = {
  // ──────── Home & Living ────────
  property: {
    id: 'property',
    route: APP_ROUTES.PROPERTY,
    verticalId: 'property',
    groupId: 'home',
    clusterIds: ['invest'],
    labelEn: ECOSYSTEM_APP_TRIPLET.property.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.property.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.property.th,
    icon: '🏠',
    status: 'active',
    personaTags: ['tourist', 'resident', 'relocation', 'family', 'couple', 'nomad', 'business'],
    bookable: true,
  },
  cleaning: {
    id: 'cleaning',
    route: APP_ROUTES.CLEANING,
    verticalId: 'cleaning',
    groupId: 'home',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.cleaning.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.cleaning.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.cleaning.th,
    icon: '🧹',
    status: 'active',
    personaTags: ['property_owner'],
    bookable: true,
  },
  babysitter: {
    id: 'babysitter',
    route: APP_ROUTES.BABYSITTER,
    verticalId: 'babysitter',
    groupId: 'home',
    clusterIds: ['family'],
    labelEn: ECOSYSTEM_APP_TRIPLET.babysitter.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.babysitter.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.babysitter.th,
    icon: '👶',
    status: 'active',
    personaTags: ['family'],
    bookable: true,
  },
  pets: {
    id: 'pets',
    route: APP_ROUTES.PETS,
    verticalId: 'pet_service',
    groupId: 'home',
    clusterIds: ['family'],
    labelEn: ECOSYSTEM_APP_TRIPLET.pets.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.pets.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.pets.th,
    icon: '🐾',
    status: 'active',
    personaTags: ['pet_owner'],
    bookable: true,
  },
  flowers: {
    id: 'flowers',
    route: APP_ROUTES.FLOWERS,
    verticalId: 'flower',
    groupId: 'home',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.flowers.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.flowers.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.flowers.th,
    icon: '💐',
    status: 'active',
    personaTags: ['tourist', 'couple'],
    bookable: true,
  },

  // ──────── Transport ────────
  transfer: {
    id: 'transfer',
    route: APP_ROUTES.AIRPORT_TRANSFER,
    verticalId: 'transfer',
    groupId: 'transport',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET.transfer.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.transfer.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.transfer.th,
    icon: '🚕',
    status: 'active',
    personaTags: ['tourist'],
    bookable: true,
  },
  vehicle: {
    id: 'vehicle',
    route: APP_ROUTES.TRANSPORT,
    verticalId: 'vehicle',
    groupId: 'transport',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET.vehicle.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.vehicle.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.vehicle.th,
    icon: '🚗',
    status: 'active',
    personaTags: ['tourist', 'nightlife', 'active'],
    bookable: true,
  },
  'fast-track': {
    id: 'fast-track',
    route: APP_ROUTES.FAST_TRACK,
    groupId: 'transport',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET['fast-track'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['fast-track'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['fast-track'].th,
    icon: '✈️',
    status: 'active',
    personaTags: ['tourist'],
    bookable: true,
  },

  // ──────── Leisure & Activities ────────
  restaurant: {
    id: 'restaurant',
    route: APP_ROUTES.RESTAURANTS,
    verticalId: 'restaurant',
    groupId: 'leisure',
    clusterIds: ['live', 'enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.restaurant.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.restaurant.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.restaurant.th,
    icon: '🍽️',
    status: 'active',
    personaTags: ['tourist', 'family', 'couple', 'nightlife', 'nomad'],
    bookable: true,
  },
  experience: {
    id: 'experience',
    route: APP_ROUTES.EXPERIENCES,
    verticalId: 'experience',
    groupId: 'leisure',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.experience.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.experience.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.experience.th,
    icon: '✨',
    status: 'active',
    personaTags: ['tourist', 'family', 'couple', 'nightlife', 'active'],
    bookable: true,
  },
  yacht: {
    id: 'yacht',
    route: APP_ROUTES.YACHTS,
    verticalId: 'yacht',
    groupId: 'leisure',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.yacht.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.yacht.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.yacht.th,
    icon: '🚤',
    status: 'active',
    personaTags: ['tourist', 'couple', 'nightlife'],
    bookable: true,
  },
  'water-activity': {
    id: 'water-activity',
    route: `${APP_ROUTES.EXPERIENCES}?type=activity`,
    verticalId: 'water_activity',
    groupId: 'leisure',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET['water-activity'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['water-activity'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['water-activity'].th,
    icon: '🏄',
    status: 'active',
    personaTags: ['active'],
    bookable: true,
  },
  event: {
    id: 'event',
    route: APP_ROUTES.EVENTS,
    verticalId: 'event',
    groupId: 'leisure',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.event.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.event.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.event.th,
    icon: '🎉',
    status: 'active',
    personaTags: ['tourist', 'active', 'couple', 'nightlife'],
    bookable: true,
  },
  fitness: {
    id: 'fitness',
    route: APP_ROUTES.FITNESS,
    verticalId: 'fitness',
    groupId: 'leisure',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.fitness.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.fitness.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.fitness.th,
    icon: '🏋️',
    status: 'active',
    personaTags: ['active', 'nomad'],
    bookable: true,
  },

  // ──────── Health & Wellness ────────
  beauty: {
    id: 'beauty',
    route: APP_ROUTES.BEAUTY,
    verticalId: 'beauty',
    groupId: 'wellness',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.beauty.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.beauty.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.beauty.th,
    icon: '💇',
    status: 'active',
    personaTags: ['couple', 'nightlife'],
    bookable: true,
  },
  medical: {
    id: 'medical',
    route: APP_ROUTES.MEDICAL,
    verticalId: 'medical',
    groupId: 'wellness',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.medical.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.medical.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.medical.th,
    icon: '🏥',
    status: 'active',
    personaTags: ['resident', 'relocation', 'family', 'active'],
    bookable: true,
  },
  pharmacy: {
    id: 'pharmacy',
    route: APP_ROUTES.PHARMACY,
    verticalId: 'pharmacy',
    groupId: 'wellness',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.pharmacy.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.pharmacy.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.pharmacy.th,
    icon: '💊',
    status: 'active',
    personaTags: ['resident', 'family'],
    bookable: false,
  },
  veterinary: {
    id: 'veterinary',
    route: APP_ROUTES.VETERINARY,
    groupId: 'wellness',
    clusterIds: ['family'],
    labelEn: ECOSYSTEM_APP_TRIPLET.veterinary.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.veterinary.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.veterinary.th,
    icon: '🐕‍🦺',
    status: 'active',
    personaTags: ['pet_owner'],
    bookable: false,
  },
  insurance: {
    id: 'insurance',
    route: APP_ROUTES.INSURANCE,
    verticalId: 'insurance',
    groupId: 'wellness',
    clusterIds: ['legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET.insurance.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.insurance.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.insurance.th,
    icon: '🛡️',
    status: 'active',
    personaTags: ['resident', 'relocation', 'investor', 'family', 'business', 'pet_owner'],
    bookable: false,
  },

  // ──────── Documents & Finance ────────
  legal: {
    id: 'legal',
    route: APP_ROUTES.LEGAL,
    verticalId: 'legal',
    groupId: 'admin_docs',
    clusterIds: ['legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET.legal.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.legal.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.legal.th,
    icon: '⚖️',
    status: 'active',
    personaTags: ['resident', 'relocation', 'investor', 'business'],
    bookable: true,
  },
  education: {
    id: 'education',
    route: APP_ROUTES.EDUCATION,
    verticalId: 'education',
    groupId: 'admin_docs',
    clusterIds: ['family'],
    labelEn: ECOSYSTEM_APP_TRIPLET.education.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.education.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.education.th,
    icon: '📚',
    status: 'active',
    personaTags: ['resident', 'relocation', 'family'],
    bookable: true,
  },
  banking: {
    id: 'banking',
    route: APP_ROUTES.BANKING,
    verticalId: 'bank',
    groupId: 'admin_docs',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET.banking.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.banking.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.banking.th,
    icon: '🏦',
    status: 'active',
    personaTags: ['resident', 'relocation', 'investor', 'nomad', 'business'],
    bookable: false,
  },
  visa: {
    id: 'visa',
    route: APP_ROUTES.VISA_IMMIGRATION,
    groupId: 'admin_docs',
    clusterIds: ['legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET.visa.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.visa.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.visa.th,
    icon: '🌍',
    status: 'active',
    personaTags: ['resident', 'relocation', 'business', 'nomad'],
    bookable: false,
  },
  relocate: {
    id: 'relocate',
    route: APP_ROUTES.RELOCATE,
    groupId: 'admin_docs',
    clusterIds: ['arrive', 'legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET.relocate.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.relocate.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.relocate.th,
    icon: '🧳',
    status: 'active',
    personaTags: ['relocation'],
    bookable: false,
  },
  tax: {
    id: 'tax',
    route: APP_ROUTES.TAX_NAV,
    groupId: 'admin_docs',
    clusterIds: ['legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET.tax.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.tax.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.tax.th,
    icon: '🧾',
    status: 'active',
    personaTags: ['resident', 'investor', 'business'],
    bookable: false,
  },
  'contract-ai': {
    id: 'contract-ai',
    route: APP_ROUTES.CONTRACT_ANALYSIS,
    groupId: 'admin_docs',
    clusterIds: ['legal'],
    labelEn: ECOSYSTEM_APP_TRIPLET['contract-ai'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['contract-ai'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['contract-ai'].th,
    icon: '🔍',
    status: 'active',
    personaTags: ['resident', 'investor', 'business'],
    bookable: false,
  },
  knowledge: {
    id: 'knowledge',
    route: APP_ROUTES.KNOWLEDGE,
    groupId: 'admin_docs',
    clusterIds: ['arrive', 'live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.knowledge.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.knowledge.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.knowledge.th,
    icon: '📖',
    status: 'active',
    personaTags: ['relocation', 'nomad'],
    bookable: false,
  },

  // ──────── Home Maintenance (sub-categories of Services) ────────
  services: {
    id: 'services',
    route: APP_ROUTES.SERVICES,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.services.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.services.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.services.th,
    icon: '🔧',
    status: 'active',
    personaTags: ['property_owner', 'business'],
    bookable: true,
  },
  'services-laundry': {
    id: 'services-laundry',
    route: `${APP_ROUTES.SERVICES}?category=laundry`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-laundry'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-laundry'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-laundry'].th,
    icon: '👕',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-plumbing': {
    id: 'services-plumbing',
    route: `${APP_ROUTES.SERVICES}?category=plumbing`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-plumbing'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-plumbing'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-plumbing'].th,
    icon: '🔧',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-electrical': {
    id: 'services-electrical',
    route: `${APP_ROUTES.SERVICES}?category=electrical`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-electrical'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-electrical'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-electrical'].th,
    icon: '⚡',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-ac': {
    id: 'services-ac',
    route: `${APP_ROUTES.SERVICES}?category=ac-repair`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-ac'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-ac'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-ac'].th,
    icon: '❄️',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-gardening': {
    id: 'services-gardening',
    route: `${APP_ROUTES.SERVICES}?category=gardening`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-gardening'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-gardening'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-gardening'].th,
    icon: '🌿',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-pest': {
    id: 'services-pest',
    route: `${APP_ROUTES.SERVICES}?category=pest-control`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-pest'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-pest'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-pest'].th,
    icon: '🐜',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-handyman': {
    id: 'services-handyman',
    route: `${APP_ROUTES.SERVICES}?category=handyman`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-handyman'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-handyman'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-handyman'].th,
    icon: '🛠️',
    status: 'active',
    personaTags: [],
    bookable: true,
  },
  'services-locksmith': {
    id: 'services-locksmith',
    route: `${APP_ROUTES.SERVICES}?category=locksmith`,
    groupId: 'maintenance',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['services-locksmith'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['services-locksmith'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['services-locksmith'].th,
    icon: '🔑',
    status: 'active',
    personaTags: [],
    bookable: true,
  },

  // ──────── Help ────────
  'vip-concierge': {
    id: 'vip-concierge',
    route: APP_ROUTES.VIP_CONCIERGE,
    groupId: 'help',
    clusterIds: ['enjoy', 'live'],
    labelEn: ECOSYSTEM_APP_TRIPLET['vip-concierge'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['vip-concierge'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['vip-concierge'].th,
    icon: '🎩',
    status: 'active',
    personaTags: ['tourist', 'resident'],
    bookable: false,
  },
  sos: {
    id: 'sos',
    route: APP_ROUTES.SOS,
    groupId: 'help',
    clusterIds: ['arrive', 'live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.sos.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.sos.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.sos.th,
    icon: '🆘',
    status: 'active',
    personaTags: ['tourist', 'resident'],
    bookable: false,
  },

  // ──────── Arrive cluster extras ────────
  sim: {
    id: 'sim',
    route: APP_ROUTES.SIM_START,
    groupId: 'transport',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET.sim.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.sim.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.sim.th,
    icon: '📱',
    status: 'active',
    personaTags: ['nomad'],
    bookable: false,
  },
  exchange: {
    id: 'exchange',
    route: APP_ROUTES.EXCHANGE,
    groupId: 'admin_docs',
    clusterIds: ['arrive'],
    labelEn: ECOSYSTEM_APP_TRIPLET.exchange.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.exchange.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.exchange.th,
    icon: '💱',
    status: 'active',
    personaTags: ['tourist', 'resident'],
    bookable: false,
  },

  // ──────── Market & Delivery ────────
  market: {
    id: 'market',
    route: APP_ROUTES.MARKET,
    groupId: 'leisure',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.market.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.market.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.market.th,
    icon: '🛍️',
    status: 'active',
    personaTags: ['tourist'],
    bookable: false,
  },
  delivery: {
    id: 'delivery',
    route: APP_ROUTES.DELIVERY,
    groupId: 'leisure',
    clusterIds: ['live'],
    labelEn: ECOSYSTEM_APP_TRIPLET.delivery.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.delivery.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.delivery.th,
    icon: '🛵',
    status: 'active',
    personaTags: ['tourist', 'resident'],
    bookable: false,
  },

  // ──────── Invest cluster ────────
  offplan: {
    id: 'offplan',
    route: APP_ROUTES.OFFPLAN,
    groupId: 'invest',
    clusterIds: ['invest'],
    labelEn: ECOSYSTEM_APP_TRIPLET.offplan.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.offplan.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.offplan.th,
    icon: '🏗️',
    status: 'active',
    personaTags: ['investor'],
    bookable: false,
  },
  resale: {
    id: 'resale',
    route: APP_ROUTES.RESALE,
    groupId: 'invest',
    clusterIds: ['invest'],
    labelEn: ECOSYSTEM_APP_TRIPLET.resale.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.resale.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.resale.th,
    icon: '🏘️',
    status: 'active',
    personaTags: ['investor'],
    bookable: false,
  },
  developers: {
    id: 'developers',
    route: APP_ROUTES.DEVELOPERS,
    groupId: 'invest',
    clusterIds: ['invest'],
    labelEn: ECOSYSTEM_APP_TRIPLET.developers.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.developers.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.developers.th,
    icon: '🏗️',
    status: 'active',
    personaTags: ['real_estate_developer'],
    bookable: false,
  },
  'invest-hub': {
    id: 'invest-hub',
    route: APP_ROUTES.INVEST,
    groupId: 'invest',
    clusterIds: ['invest'],
    labelEn: ECOSYSTEM_APP_TRIPLET['invest-hub'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['invest-hub'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['invest-hub'].th,
    icon: '📈',
    status: 'active',
    personaTags: ['investor'],
    bookable: false,
  },

  // ──────── Manage cluster ────────
  mc: {
    id: 'mc',
    route: APP_ROUTES.MC,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET.mc.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.mc.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.mc.th,
    icon: '📅',
    status: 'active',
    personaTags: ['property_owner'],
    bookable: false,
  },
  'mc-calendar': {
    id: 'mc-calendar',
    route: APP_ROUTES.MC_CALENDAR,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET['mc-calendar'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['mc-calendar'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['mc-calendar'].th,
    icon: '📅',
    status: 'active',
    personaTags: ['property_owner'],
    bookable: false,
  },
  'mc-tasks': {
    id: 'mc-tasks',
    route: APP_ROUTES.MC_TASKS,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET['mc-tasks'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['mc-tasks'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['mc-tasks'].th,
    icon: '✅',
    status: 'active',
    personaTags: ['property_owner'],
    bookable: false,
  },
  'mc-finance': {
    id: 'mc-finance',
    route: APP_ROUTES.MC_FINANCE,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET['mc-finance'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['mc-finance'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['mc-finance'].th,
    icon: '💰',
    status: 'active',
    personaTags: ['property_owner'],
    bookable: false,
  },
  'mc-reports': {
    id: 'mc-reports',
    route: APP_ROUTES.MC_REPORTS,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET['mc-reports'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['mc-reports'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['mc-reports'].th,
    icon: '📊',
    status: 'pro',
    personaTags: [],
    bookable: false,
  },
  'mc-crm': {
    id: 'mc-crm',
    route: APP_ROUTES.MC_CRM_DASHBOARD,
    groupId: 'manage',
    clusterIds: ['manage'],
    labelEn: ECOSYSTEM_APP_TRIPLET['mc-crm'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['mc-crm'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['mc-crm'].th,
    icon: '👥',
    status: 'pro',
    personaTags: ['property_owner'],
    bookable: false,
  },

  // ──────── Build / For Developers ────────
  'developer-portal': {
    id: 'developer-portal',
    route: APP_ROUTES.DEVELOPER_PORTAL,
    groupId: 'build',
    clusterIds: ['build'],
    labelEn: ECOSYSTEM_APP_TRIPLET['developer-portal'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['developer-portal'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['developer-portal'].th,
    icon: '🏢',
    status: 'active',
    personaTags: ['real_estate_developer'],
    bookable: false,
  },
  'for-developers': {
    id: 'for-developers',
    route: APP_ROUTES.FOR_REAL_ESTATE_DEVELOPERS,
    groupId: 'build',
    clusterIds: ['build'],
    labelEn: ECOSYSTEM_APP_TRIPLET['for-developers'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['for-developers'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['for-developers'].th,
    icon: '📋',
    status: 'active',
    personaTags: ['real_estate_developer'],
    bookable: false,
  },
  newbuilds: {
    id: 'newbuilds',
    route: APP_ROUTES.NEWBUILDS,
    groupId: 'build',
    clusterIds: ['build'],
    labelEn: ECOSYSTEM_APP_TRIPLET.newbuilds.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.newbuilds.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.newbuilds.th,
    icon: '🏗️',
    status: 'active',
    personaTags: ['real_estate_developer', 'investor'],
    bookable: false,
  },
  consultation: {
    id: 'consultation',
    route: APP_ROUTES.PROPERTY_CONSULTATION,
    groupId: 'build',
    clusterIds: ['build'],
    labelEn: ECOSYSTEM_APP_TRIPLET.consultation.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.consultation.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.consultation.th,
    icon: '📞',
    status: 'active',
    personaTags: ['real_estate_developer'],
    bookable: false,
  },

  // ──────── Lifestyle landings ────────
  'school-finder': {
    id: 'school-finder',
    route: APP_ROUTES.SCHOOL_FINDER,
    groupId: 'lifestyle',
    clusterIds: ['family'],
    labelEn: ECOSYSTEM_APP_TRIPLET['school-finder'].en,
    labelRu: ECOSYSTEM_APP_TRIPLET['school-finder'].ru,
    labelTh: ECOSYSTEM_APP_TRIPLET['school-finder'].th,
    icon: '🎓',
    status: 'active',
    personaTags: ['family'],
    bookable: false,
  },

  // ──────── Previously uncataloged — now in journey groups (deduped — primary defs above) ────────
  wedding: {
    id: 'wedding',
    route: APP_ROUTES.WEDDING,
    groupId: 'enjoy',
    clusterIds: ['enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.wedding.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.wedding.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.wedding.th,
    icon: '💍',
    status: 'active',
    personaTags: ['couple'],
    bookable: false,
  },
  kids: {
    id: 'kids',
    route: APP_ROUTES.KIDS,
    groupId: 'enjoy',
    clusterIds: ['family', 'enjoy'],
    labelEn: ECOSYSTEM_APP_TRIPLET.kids.en,
    labelRu: ECOSYSTEM_APP_TRIPLET.kids.ru,
    labelTh: ECOSYSTEM_APP_TRIPLET.kids.th,
    icon: '🎈',
    status: 'active',
    personaTags: ['family'],
    bookable: false,
  },
} as const satisfies Record<string, AppEntry>;

// ── Derived helpers ──

export function getAppsForGroup(groupId: AppGroupId): AppEntry[] {
  return Object.values(APP_REGISTRY).filter((e) => e.groupId === groupId);
}

export function getAppsForCluster(clusterId: NavigatorClusterId): AppEntry[] {
  return Object.values(APP_REGISTRY).filter((e) => e.clusterIds.includes(clusterId));
}

export function getAppsForPersona(personaTag: string): AppEntry[] {
  return Object.values(APP_REGISTRY).filter((e) => e.personaTags.includes(personaTag));
}

export function getActiveApps(): AppEntry[] {
  return Object.values(APP_REGISTRY).filter((e) => e.status === 'active');
}
