import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InvoiceData {
  invoice_number: string;
  recipient_name: string;
  recipient_email?: string;
  issued_date: string;
  due_date?: string;
  items: { description: string; quantity: number; unit_price: number; amount: number }[];
  subtotal: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  currency: string;
  notes?: string;
  status: string;
}

export function generateInvoicePdf(invoice: InvoiceData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(33, 33, 33);
  doc.text('INVOICE', 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`#${invoice.invoice_number}`, 20, 38);

  // Status badge
  doc.setFontSize(11);
  doc.setTextColor(
    invoice.status === 'paid' ? 34 : invoice.status === 'overdue' ? 220 : 66,
    invoice.status === 'paid' ? 139 : invoice.status === 'overdue' ? 53 : 66,
    invoice.status === 'paid' ? 34 : invoice.status === 'overdue' ? 69 : 66
  );
  doc.text(invoice.status.toUpperCase(), pageWidth - 20, 30, { align: 'right' });

  // Dates
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Issued: ${invoice.issued_date}`, pageWidth - 20, 40, { align: 'right' });
  if (invoice.due_date) {
    doc.text(`Due: ${invoice.due_date}`, pageWidth - 20, 46, { align: 'right' });
  }

  // Bill To
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Bill To:', 20, 55);
  doc.setFontSize(12);
  doc.setTextColor(33, 33, 33);
  doc.text(invoice.recipient_name, 20, 62);
  if (invoice.recipient_email) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(invoice.recipient_email, 20, 68);
  }

  // Items table
  const tableData = invoice.items.map(item => [
    item.description,
    item.quantity.toString(),
    `${item.unit_price.toLocaleString()} ${invoice.currency}`,
    `${item.amount.toLocaleString()} ${invoice.currency}`,
  ]);

  autoTable(doc, {
    startY: 78,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [50, 50, 50], textColor: [255, 255, 255], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'center', cellWidth: 25 },
      2: { halign: 'right', cellWidth: 40 },
      3: { halign: 'right', cellWidth: 40 },
    },
  });

  // Totals
  const finalY = (doc as any).lastAutoTable?.finalY || 120;
  const totalsY = finalY + 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Subtotal:', pageWidth - 70, totalsY);
  doc.text(`${invoice.subtotal.toLocaleString()} ${invoice.currency}`, pageWidth - 20, totalsY, { align: 'right' });

  if (invoice.tax_amount > 0) {
    doc.text(`Tax (${invoice.tax_rate}%):`, pageWidth - 70, totalsY + 7);
    doc.text(`${invoice.tax_amount.toLocaleString()} ${invoice.currency}`, pageWidth - 20, totalsY + 7, { align: 'right' });
  }

  doc.setFontSize(13);
  doc.setTextColor(33, 33, 33);
  const totalLineY = invoice.tax_amount > 0 ? totalsY + 17 : totalsY + 10;
  doc.line(pageWidth - 80, totalLineY - 3, pageWidth - 20, totalLineY - 3);
  doc.text('Total:', pageWidth - 70, totalLineY + 3);
  doc.text(`${invoice.total.toLocaleString()} ${invoice.currency}`, pageWidth - 20, totalLineY + 3, { align: 'right' });

  // Notes
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Notes:', 20, totalLineY + 20);
    doc.text(invoice.notes, 20, totalLineY + 26, { maxWidth: pageWidth - 40 });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by myUNO', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc;
}
