// jsPDF is loaded lazily to avoid 380KB in the main bundle

interface InvoiceData {
  invoice_number: string;
  recipient_name: string;
  recipient_email?: string;
  issued_date: string;
  due_date?: string;
  items: { description: string; quantity: number; unit_price: number; amount: number }[];
  subtotal: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  currency: string;
  notes?: string;
  status: string;
}

export async function generateInvoicePdf(invoice: InvoiceData) {
  const { default: jsPDF } = await import('jspdf');
  await import('jspdf-autotable');
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(33, 33, 33);
  doc.text('INVOICE', 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`#${invoice.invoice_number}`, 20, 38);
  doc.text(`Status: ${invoice.status.toUpperCase()}`, pageWidth - 20, 30, { align: 'right' });

  // Dates
  doc.setFontSize(9);
  doc.text(`Issued: ${invoice.issued_date}`, 20, 50);
  if (invoice.due_date) {
    doc.text(`Due: ${invoice.due_date}`, 20, 56);
  }

  // Recipient
  doc.setFontSize(10);
  doc.setTextColor(33, 33, 33);
  doc.text('Bill To:', 20, 68);
  doc.setFontSize(11);
  doc.text(invoice.recipient_name, 20, 74);
  if (invoice.recipient_email) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(invoice.recipient_email, 20, 80);
  }

  // Items table
  const tableData = invoice.items.map(item => [
    item.description,
    item.quantity.toString(),
    `${invoice.currency} ${item.unit_price.toLocaleString()}`,
    `${invoice.currency} ${item.amount.toLocaleString()}`,
  ]);

  (doc as any).autoTable({
    startY: 90,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [26, 115, 232], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 80 },
      1: { halign: 'center', cellWidth: 25 },
      2: { halign: 'right', cellWidth: 35 },
      3: { halign: 'right', cellWidth: 35 },
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 150;

  // Totals
  doc.setFontSize(10);
  doc.setTextColor(33, 33, 33);
  const totalsX = pageWidth - 70;
  doc.text('Subtotal:', totalsX, finalY + 15);
  doc.text(`${invoice.currency} ${invoice.subtotal.toLocaleString()}`, pageWidth - 20, finalY + 15, { align: 'right' });

  doc.text(`Tax (${invoice.tax_rate}%):`, totalsX, finalY + 22);
  doc.text(`${invoice.currency} ${invoice.tax_amount.toLocaleString()}`, pageWidth - 20, finalY + 22, { align: 'right' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', totalsX, finalY + 32);
  doc.text(`${invoice.currency} ${invoice.total.toLocaleString()}`, pageWidth - 20, finalY + 32, { align: 'right' });

  // Notes
  if (invoice.notes) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Notes:', 20, finalY + 50);
    doc.text(invoice.notes, 20, finalY + 56, { maxWidth: pageWidth - 40 });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by myUNO', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc;
}
