import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.discover': 'Каталог',
    'nav.map': 'Карта',
    'nav.support': 'Чат',
    'nav.bookings': 'Брони',
    'nav.profile': 'Профиль',
    
    // Auth
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.logout': 'Выйти',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.fullName': 'Полное имя',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.createAccount': 'Создать аккаунт',
    'auth.welcomeBack': 'С возвращением!',
    'auth.getStarted': 'Начните сейчас',
    
    // Common actions
    'action.book': 'Забронировать',
    'action.cancel': 'Отмена',
    'action.confirm': 'Подтвердить',
    'action.save': 'Сохранить',
    'action.edit': 'Редактировать',
    'action.delete': 'Удалить',
    'action.view': 'Смотреть',
    'action.viewAll': 'Смотреть все',
    'action.search': 'Поиск',
    'action.filter': 'Фильтр',
    'action.sort': 'Сортировка',
    'action.apply': 'Применить',
    'action.clear': 'Очистить',
    'action.back': 'Назад',
    'action.next': 'Далее',
    'action.submit': 'Отправить',
    
    // Booking statuses
    'status.draft': 'Черновик',
    'status.submitted': 'Отправлено',
    'status.confirmed': 'Подтверждено',
    'status.in_progress': 'В процессе',
    'status.completed': 'Завершено',
    'status.cancelled_by_user': 'Отменено вами',
    'status.cancelled_by_provider': 'Отменено исполнителем',
    'status.expired': 'Истекло',
    
    // Categories
    'category.beauty-spa': 'Красота',
    'category.restaurants': 'Еда',
    'category.flowers': 'Цветы',
    'category.fitness': 'Фитнес',
    'category.medical': 'Медицина',
    'category.kids-education': 'Обучение',
    'category.real-estate': 'Жильё',
    'category.transport': 'Транспорт',
    'category.events': 'События',
    'category.shopping': 'Покупки',
    'category.services': 'Услуги',
    'category.legal': 'Бизнес',
    'category.tours': 'Туры',
    'category.water': 'Вода',
    'category.pharmacy': 'Аптеки',
    
    // Hero section
    'home.heroTitle': 'Дом там, где UNO',
    'home.heroSubtitle': 'Твоя жизнь за рубежом — проще',
    'home.trustBadge': 'Проверено',
    
    // Tours
    'tours.title': 'Экскурсии и туры',
    'tours.subtitle': 'Откройте для себя Пхукет',
    'tours.featured': 'Популярные туры',
    'tours.duration': 'Длительность',
    'tours.includes': 'Включено',
    'tours.itinerary': 'Маршрут',
    'tours.meetingPoint': 'Место встречи',
    'tours.maxParticipants': 'Макс. участников',
    'tours.difficulty': 'Сложность',
    'tours.highlights': 'Особенности',
    'tours.bookNow': 'Забронировать тур',
    'tours.selectDate': 'Выберите дату',
    'tours.selectTime': 'Выберите время',
    'tours.participants': 'Участники',
    'tours.contactDetails': 'Контактные данные',
    'tours.confirmBooking': 'Подтвердить бронирование',
    'tours.bookingSuccess': 'Тур забронирован!',
    'tours.notFound': 'Тур не найден',
    'tours.description': 'Описание',
    'tours.perPerson': '/чел',
    'tours.booking': 'Бронирование тура',
    'tours.name': 'Имя',
    'tours.phone': 'Телефон',
    'tours.total': 'Итого',
    'tours.fillAllFields': 'Заполните все поля',
    'tours.bookingSent': 'Заявка отправлена',
    'tours.bookingFailed': 'Не удалось забронировать',
    
    // Water Activities
    'water.title': 'Водные активности',
    'water.subtitle': 'Дайвинг, снорклинг, яхты и многое другое',
    'water.featured': 'Популярные активности',
    'water.diving': 'Дайвинг',
    'water.snorkeling': 'Снорклинг',
    'water.jetski': 'Гидроцикл',
    'water.yacht': 'Яхты',
    'water.surfing': 'Серфинг',
    'water.kayaking': 'Каякинг',
    'water.fishing': 'Рыбалка',
    'water.parasailing': 'Парасейлинг',
    'water.certified': 'Сертифицировано',
    'water.equipmentIncluded': 'Снаряжение включено',
    'water.safetyBriefing': 'Инструктаж по безопасности',
    'water.ageRestriction': 'Минимальный возраст',
    'water.difficulty.easy': 'Легкий',
    'water.difficulty.moderate': 'Средний',
    'water.difficulty.challenging': 'Сложный',
    'water.difficulty.expert': 'Эксперт',
    'water.notFound': 'Активность не найдена',
    'water.goBack': 'Назад',
    'water.description': 'Описание',
    'water.whatsIncluded': 'Что включено',
    'water.requirements': 'Требования',
    'water.safety': 'Безопасность',
    'water.safetyRequired': 'Обязательный инструктаж по безопасности',
    'water.minAge': 'Минимальный возраст',
    'water.years': 'лет',
    'water.meetingPoint': 'Место встречи',
    'water.availableTimes': 'Доступное время',
    'water.bookNow': 'Забронировать',
    'water.pricePer': 'Цена за',
    'water.upTo': 'до',
    'water.max': 'макс',
    
    // Pharmacy
    'pharmacy.title': 'Аптеки',
    'pharmacy.subtitle': 'Лекарства и товары для здоровья',
    'pharmacy.24h': 'Круглосуточно',
    'pharmacy.delivery': 'Доставка',
    'pharmacy.fastDelivery': 'Быстрая доставка',
    'pharmacy.fromMinutes': 'От 30 минут',
    'pharmacy.pharmacist': 'Консультация фармацевта',
    'pharmacy.pharmacistAvailable': 'Есть фармацевт',
    'pharmacy.prescription': 'По рецепту',
    'pharmacy.products': 'Товары',
    'pharmacy.general': 'Общие',
    'pharmacy.vitamins': 'Витамины',
    'pharmacy.firstAid': 'Первая помощь',
    'pharmacy.skincare': 'Уход за кожей',
    'pharmacy.personalCare': 'Личная гигиена',
    'pharmacy.addToCart': 'В корзину',
    'pharmacy.addedToCart': 'Добавлено в корзину',
    'pharmacy.cart': 'Корзина',
    'pharmacy.minOrder': 'Минимальный заказ',
    'pharmacy.deliveryFee': 'Стоимость доставки',
    'pharmacy.deliveryFrom': 'Доставка от',
    'pharmacy.notFound': 'Аптека не найдена',
    'pharmacy.noProducts': 'Товары не найдены',
    'pharmacy.verified': 'Проверено',
    'pharmacy.all': 'Все',
    
    // User types
    'userType.tourist': 'Турист',
    'userType.resident': 'Резидент',
    
    // Common labels
    'label.price': 'Цена',
    'label.duration': 'Длительность',
    'label.rating': 'Рейтинг',
    'label.reviews': 'отзывов',
    'label.location': 'Локация',
    'label.date': 'Дата',
    'label.time': 'Время',
    'label.from': 'от',
    'label.perHour': '/час',
    'label.perDay': '/день',
    'label.perNight': '/ночь',
    'label.verified': 'Проверено',
    'label.popular': 'Популярное',
    'label.new': 'Новое',
    'label.featured': 'Рекомендуем',
    
    // Messages
    'message.noResults': 'Ничего не найдено',
    'message.loading': 'Загрузка...',
    'message.error': 'Произошла ошибка',
    'message.success': 'Успешно!',
    'message.loginRequired': 'Требуется авторизация',
    
    // Home page
    'home.welcome': 'Добро пожаловать в UNO',
    'home.subtitle': 'Ваш персональный гид по Пхукету',
    'home.featuredServices': 'Популярные услуги',
    'home.categories': 'Категории',
    'home.nearYou': 'Рядом с вами',
    
    // Beauty & Spa
    'beauty.title': 'Красота и СПА',
    'beauty.salons': 'Салоны',
    'beauty.services': 'Услуги',
    'beauty.selectServices': 'Выберите услуги',
    'beauty.popularServices': 'Популярные услуги',
    'beauty.nearbySalons': 'Салоны рядом',
    'beauty.searchSalons': 'Поиск салонов...',
    'beauty.searchServices': 'Поиск услуг...',
    'beauty.bookAppointment': 'Записаться',
    'beauty.selectDate': 'Выберите дату',
    'beauty.selectTime': 'Выберите время',
    'beauty.contactInfo': 'Контактная информация',
    'beauty.confirmBooking': 'Подтвердить бронирование',
    'beauty.bookingSuccess': 'Бронирование создано!',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.discover': 'Discover',
    'nav.map': 'Map',
    'nav.support': 'Chat',
    'nav.bookings': 'Bookings',
    'nav.profile': 'Profile',
    
    // Auth
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Log Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome Back!',
    'auth.getStarted': 'Get Started',
    
    // Common actions
    'action.book': 'Book Now',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.save': 'Save',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.view': 'View',
    'action.viewAll': 'View All',
    'action.search': 'Search',
    'action.filter': 'Filter',
    'action.sort': 'Sort',
    'action.apply': 'Apply',
    'action.clear': 'Clear',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.submit': 'Submit',
    
    // Booking statuses
    'status.draft': 'Draft',
    'status.submitted': 'Submitted',
    'status.confirmed': 'Confirmed',
    'status.in_progress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled_by_user': 'Cancelled by You',
    'status.cancelled_by_provider': 'Cancelled by Provider',
    'status.expired': 'Expired',
    
    // Categories (short names)
    'category.beauty-spa': 'Beauty',
    'category.restaurants': 'Food',
    'category.flowers': 'Flowers',
    'category.fitness': 'Fitness',
    'category.medical': 'Medical',
    'category.kids-education': 'Education',
    'category.real-estate': 'Housing',
    'category.transport': 'Transport',
    'category.events': 'Events',
    'category.shopping': 'Shopping',
    'category.services': 'Services',
    'category.legal': 'Business',
    'category.tours': 'Tours',
    'category.water': 'Water',
    'category.pharmacy': 'Pharmacy',
    
    // Hero section
    'home.heroTitle': 'Home is where UNO is',
    'home.heroSubtitle': 'Your life abroad, simplified',
    'home.trustBadge': 'Verified',
    
    // Tours
    'tours.title': 'Tours & Excursions',
    'tours.subtitle': 'Discover Phuket',
    'tours.featured': 'Featured Tours',
    'tours.duration': 'Duration',
    'tours.includes': 'Includes',
    'tours.itinerary': 'Itinerary',
    'tours.meetingPoint': 'Meeting Point',
    'tours.maxParticipants': 'Max Participants',
    'tours.difficulty': 'Difficulty',
    'tours.highlights': 'Highlights',
    'tours.bookNow': 'Book Tour',
    'tours.selectDate': 'Select Date',
    'tours.selectTime': 'Select Time',
    'tours.participants': 'Participants',
    'tours.contactDetails': 'Contact Details',
    'tours.confirmBooking': 'Confirm Booking',
    'tours.bookingSuccess': 'Tour Booked!',
    'tours.notFound': 'Tour not found',
    'tours.description': 'Description',
    'tours.perPerson': '/person',
    'tours.booking': 'Book Tour',
    'tours.name': 'Name',
    'tours.phone': 'Phone',
    'tours.total': 'Total',
    'tours.fillAllFields': 'Fill all fields',
    'tours.bookingSent': 'Booking sent',
    'tours.bookingFailed': 'Booking failed',
    
    // Water Activities
    'water.title': 'Water Activities',
    'water.subtitle': 'Diving, snorkeling, yachts and more',
    'water.featured': 'Featured Activities',
    'water.diving': 'Diving',
    'water.snorkeling': 'Snorkeling',
    'water.jetski': 'Jet Ski',
    'water.yacht': 'Yachts',
    'water.surfing': 'Surfing',
    'water.kayaking': 'Kayaking',
    'water.fishing': 'Fishing',
    'water.parasailing': 'Parasailing',
    'water.certified': 'Certified',
    'water.equipmentIncluded': 'Equipment Included',
    'water.safetyBriefing': 'Safety Briefing',
    'water.ageRestriction': 'Minimum Age',
    'water.difficulty.easy': 'Easy',
    'water.difficulty.moderate': 'Moderate',
    'water.difficulty.challenging': 'Challenging',
    'water.difficulty.expert': 'Expert',
    'water.notFound': 'Activity not found',
    'water.goBack': 'Go Back',
    'water.description': 'Description',
    'water.whatsIncluded': "What's Included",
    'water.requirements': 'Requirements',
    'water.safety': 'Safety',
    'water.safetyRequired': 'Safety briefing required',
    'water.minAge': 'Minimum age',
    'water.years': 'years',
    'water.meetingPoint': 'Meeting Point',
    'water.availableTimes': 'Available Times',
    'water.bookNow': 'Book Now',
    'water.pricePer': 'Price per',
    'water.upTo': 'up to',
    'water.max': 'max',
    
    // Pharmacy
    'pharmacy.title': 'Pharmacies',
    'pharmacy.subtitle': 'Medicine and health products',
    'pharmacy.24h': '24/7',
    'pharmacy.delivery': 'Delivery',
    'pharmacy.fastDelivery': 'Fast Delivery',
    'pharmacy.fromMinutes': 'From 30 min',
    'pharmacy.pharmacist': 'Pharmacist Consultation',
    'pharmacy.pharmacistAvailable': 'Pharmacist available',
    'pharmacy.prescription': 'Prescription Required',
    'pharmacy.products': 'Products',
    'pharmacy.general': 'General',
    'pharmacy.vitamins': 'Vitamins',
    'pharmacy.firstAid': 'First Aid',
    'pharmacy.skincare': 'Skincare',
    'pharmacy.personalCare': 'Personal Care',
    'pharmacy.addToCart': 'Add to Cart',
    'pharmacy.addedToCart': 'Added to cart',
    'pharmacy.cart': 'Cart',
    'pharmacy.minOrder': 'Minimum Order',
    'pharmacy.deliveryFee': 'Delivery Fee',
    'pharmacy.deliveryFrom': 'Delivery from',
    'pharmacy.notFound': 'Pharmacy not found',
    'pharmacy.noProducts': 'No products found',
    'pharmacy.verified': 'Verified',
    'pharmacy.all': 'All',
    
    // User types
    'userType.tourist': 'Tourist',
    'userType.resident': 'Resident',
    
    // Common labels
    'label.price': 'Price',
    'label.duration': 'Duration',
    'label.rating': 'Rating',
    'label.reviews': 'reviews',
    'label.location': 'Location',
    'label.date': 'Date',
    'label.time': 'Time',
    'label.from': 'from',
    'label.perHour': '/hr',
    'label.perDay': '/day',
    'label.perNight': '/night',
    'label.verified': 'Verified',
    'label.popular': 'Popular',
    'label.new': 'New',
    'label.featured': 'Featured',
    
    // Messages
    'message.noResults': 'No results found',
    'message.loading': 'Loading...',
    'message.error': 'An error occurred',
    'message.success': 'Success!',
    'message.loginRequired': 'Login required',
    
    // Home page
    'home.welcome': 'Welcome to UNO',
    'home.subtitle': 'Your personal guide to Phuket',
    'home.featuredServices': 'Featured Services',
    'home.categories': 'Categories',
    'home.nearYou': 'Near You',
    
    // Beauty & Spa
    'beauty.title': 'Beauty & Spa',
    'beauty.salons': 'Salons',
    'beauty.services': 'Services',
    'beauty.selectServices': 'Select Services',
    'beauty.popularServices': 'Popular Services',
    'beauty.nearbySalons': 'Nearby Salons',
    'beauty.searchSalons': 'Search salons...',
    'beauty.searchServices': 'Search services...',
    'beauty.bookAppointment': 'Book Appointment',
    'beauty.selectDate': 'Select Date',
    'beauty.selectTime': 'Select Time',
    'beauty.contactInfo': 'Contact Information',
    'beauty.confirmBooking': 'Confirm Booking',
    'beauty.bookingSuccess': 'Booking Confirmed!',
  },
  th: {
    // Navigation
    'nav.home': 'หน้าแรก',
    'nav.discover': 'ค้นหา',
    'nav.map': 'แผนที่',
    'nav.support': 'แชท',
    'nav.bookings': 'การจอง',
    'nav.profile': 'โปรไฟล์',
    
    // Auth
    'auth.login': 'เข้าสู่ระบบ',
    'auth.signup': 'สมัครสมาชิก',
    'auth.logout': 'ออกจากระบบ',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.fullName': 'ชื่อเต็ม',
    'auth.forgotPassword': 'ลืมรหัสผ่าน?',
    'auth.noAccount': 'ยังไม่มีบัญชี?',
    'auth.hasAccount': 'มีบัญชีอยู่แล้ว?',
    'auth.createAccount': 'สร้างบัญชี',
    'auth.welcomeBack': 'ยินดีต้อนรับกลับ!',
    'auth.getStarted': 'เริ่มต้นใช้งาน',
    
    // Common actions
    'action.book': 'จองเลย',
    'action.cancel': 'ยกเลิก',
    'action.confirm': 'ยืนยัน',
    'action.save': 'บันทึก',
    'action.edit': 'แก้ไข',
    'action.delete': 'ลบ',
    'action.view': 'ดู',
    'action.viewAll': 'ดูทั้งหมด',
    'action.search': 'ค้นหา',
    'action.filter': 'กรอง',
    'action.sort': 'เรียงลำดับ',
    'action.apply': 'ใช้งาน',
    'action.clear': 'ล้าง',
    'action.back': 'กลับ',
    'action.next': 'ถัดไป',
    'action.submit': 'ส่ง',
    
    // Booking statuses
    'status.draft': 'ฉบับร่าง',
    'status.submitted': 'ส่งแล้ว',
    'status.confirmed': 'ยืนยันแล้ว',
    'status.in_progress': 'กำลังดำเนินการ',
    'status.completed': 'เสร็จสิ้น',
    'status.cancelled_by_user': 'ยกเลิกโดยคุณ',
    'status.cancelled_by_provider': 'ยกเลิกโดยผู้ให้บริการ',
    'status.expired': 'หมดอายุ',
    
    // Categories
    'category.beauty-spa': 'ความงาม',
    'category.restaurants': 'อาหาร',
    'category.flowers': 'ดอกไม้',
    'category.fitness': 'ฟิตเนส',
    'category.medical': 'การแพทย์',
    'category.kids-education': 'การศึกษา',
    'category.real-estate': 'ที่พัก',
    'category.transport': 'ขนส่ง',
    'category.events': 'กิจกรรม',
    'category.shopping': 'ช้อปปิ้ง',
    'category.services': 'บริการ',
    'category.legal': 'ธุรกิจ',
    'category.tours': 'ทัวร์',
    'category.water': 'กิจกรรมทางน้ำ',
    'category.pharmacy': 'ร้านขายยา',
    
    // Hero section
    'home.heroTitle': 'บ้านอยู่ที่ไหน UNO อยู่ที่นั่น',
    'home.heroSubtitle': 'ชีวิตต่างแดนของคุณ ง่ายขึ้น',
    'home.trustBadge': 'ยืนยันแล้ว',
    
    // Tours
    'tours.title': 'ทัวร์และทริป',
    'tours.subtitle': 'ค้นพบภูเก็ต',
    'tours.featured': 'ทัวร์ยอดนิยม',
    'tours.duration': 'ระยะเวลา',
    'tours.includes': 'รวม',
    'tours.itinerary': 'กำหนดการ',
    'tours.meetingPoint': 'จุดนัดพบ',
    'tours.maxParticipants': 'ผู้เข้าร่วมสูงสุด',
    'tours.difficulty': 'ระดับความยาก',
    'tours.highlights': 'ไฮไลท์',
    'tours.bookNow': 'จองทัวร์',
    'tours.selectDate': 'เลือกวันที่',
    'tours.selectTime': 'เลือกเวลา',
    'tours.participants': 'ผู้เข้าร่วม',
    'tours.contactDetails': 'ข้อมูลติดต่อ',
    'tours.confirmBooking': 'ยืนยันการจอง',
    'tours.bookingSuccess': 'จองทัวร์สำเร็จ!',
    'tours.notFound': 'ไม่พบทัวร์',
    'tours.description': 'รายละเอียด',
    'tours.perPerson': '/คน',
    'tours.booking': 'จองทัวร์',
    'tours.name': 'ชื่อ',
    'tours.phone': 'โทรศัพท์',
    'tours.total': 'รวม',
    'tours.fillAllFields': 'กรุณากรอกข้อมูลให้ครบ',
    'tours.bookingSent': 'ส่งการจองแล้ว',
    'tours.bookingFailed': 'การจองล้มเหลว',
    
    // Water Activities
    'water.title': 'กิจกรรมทางน้ำ',
    'water.subtitle': 'ดำน้ำ สน็อกเกิล เรือยอร์ช และอื่นๆ',
    'water.featured': 'กิจกรรมยอดนิยม',
    'water.diving': 'ดำน้ำ',
    'water.snorkeling': 'สน็อกเกิล',
    'water.jetski': 'เจ็ตสกี',
    'water.yacht': 'เรือยอร์ช',
    'water.surfing': 'เซิร์ฟ',
    'water.kayaking': 'พายเรือ',
    'water.fishing': 'ตกปลา',
    'water.parasailing': 'ร่มร่อน',
    'water.certified': 'ได้รับการรับรอง',
    'water.equipmentIncluded': 'รวมอุปกรณ์',
    'water.safetyBriefing': 'บรรยายสรุปความปลอดภัย',
    'water.ageRestriction': 'อายุขั้นต่ำ',
    'water.difficulty.easy': 'ง่าย',
    'water.difficulty.moderate': 'ปานกลาง',
    'water.difficulty.challenging': 'ท้าทาย',
    'water.difficulty.expert': 'ผู้เชี่ยวชาญ',
    'water.notFound': 'ไม่พบกิจกรรม',
    'water.goBack': 'กลับ',
    'water.description': 'รายละเอียด',
    'water.whatsIncluded': 'รวมอะไรบ้าง',
    'water.requirements': 'ข้อกำหนด',
    'water.safety': 'ความปลอดภัย',
    'water.safetyRequired': 'ต้องมีการบรรยายสรุปความปลอดภัย',
    'water.minAge': 'อายุขั้นต่ำ',
    'water.years': 'ปี',
    'water.meetingPoint': 'จุดนัดพบ',
    'water.availableTimes': 'เวลาที่เปิดให้บริการ',
    'water.bookNow': 'จองเลย',
    'water.pricePer': 'ราคาต่อ',
    'water.upTo': 'สูงสุด',
    'water.max': 'สูงสุด',
    
    // Pharmacy
    'pharmacy.title': 'ร้านขายยา',
    'pharmacy.subtitle': 'ยาและผลิตภัณฑ์สุขภาพ',
    'pharmacy.24h': '24 ชม.',
    'pharmacy.delivery': 'จัดส่ง',
    'pharmacy.fastDelivery': 'จัดส่งด่วน',
    'pharmacy.fromMinutes': 'ภายใน 30 นาที',
    'pharmacy.pharmacist': 'ปรึกษาเภสัชกร',
    'pharmacy.pharmacistAvailable': 'มีเภสัชกร',
    'pharmacy.prescription': 'ต้องมีใบสั่งยา',
    'pharmacy.products': 'สินค้า',
    'pharmacy.general': 'ทั่วไป',
    'pharmacy.vitamins': 'วิตามิน',
    'pharmacy.firstAid': 'ปฐมพยาบาล',
    'pharmacy.skincare': 'ดูแลผิว',
    'pharmacy.personalCare': 'ของใช้ส่วนตัว',
    'pharmacy.addToCart': 'เพิ่มในตะกร้า',
    'pharmacy.addedToCart': 'เพิ่มในตะกร้าแล้ว',
    'pharmacy.cart': 'ตะกร้า',
    'pharmacy.minOrder': 'สั่งขั้นต่ำ',
    'pharmacy.deliveryFee': 'ค่าจัดส่ง',
    'pharmacy.deliveryFrom': 'จัดส่งจาก',
    'pharmacy.notFound': 'ไม่พบร้านขายยา',
    'pharmacy.noProducts': 'ไม่พบสินค้า',
    'pharmacy.verified': 'ยืนยันแล้ว',
    'pharmacy.all': 'ทั้งหมด',
    
    // User types
    'userType.tourist': 'นักท่องเที่ยว',
    'userType.resident': 'ผู้พักอาศัย',
    
    // Common labels
    'label.price': 'ราคา',
    'label.duration': 'ระยะเวลา',
    'label.rating': 'คะแนน',
    'label.reviews': 'รีวิว',
    'label.location': 'สถานที่',
    'label.date': 'วันที่',
    'label.time': 'เวลา',
    'label.from': 'จาก',
    'label.perHour': '/ชม.',
    'label.perDay': '/วัน',
    'label.perNight': '/คืน',
    'label.verified': 'ยืนยันแล้ว',
    'label.popular': 'ยอดนิยม',
    'label.new': 'ใหม่',
    'label.featured': 'แนะนำ',
    
    // Messages
    'message.noResults': 'ไม่พบผลลัพธ์',
    'message.loading': 'กำลังโหลด...',
    'message.error': 'เกิดข้อผิดพลาด',
    'message.success': 'สำเร็จ!',
    'message.loginRequired': 'กรุณาเข้าสู่ระบบ',
    
    // Home page
    'home.welcome': 'ยินดีต้อนรับสู่ UNO',
    'home.subtitle': 'ไกด์ส่วนตัวของคุณในภูเก็ต',
    'home.featuredServices': 'บริการยอดนิยม',
    'home.categories': 'หมวดหมู่',
    'home.nearYou': 'ใกล้คุณ',
    
    // Beauty & Spa
    'beauty.title': 'ความงามและสปา',
    'beauty.salons': 'ร้าน',
    'beauty.services': 'บริการ',
    'beauty.selectServices': 'เลือกบริการ',
    'beauty.popularServices': 'บริการยอดนิยม',
    'beauty.nearbySalons': 'ร้านใกล้เคียง',
    'beauty.searchSalons': 'ค้นหาร้าน...',
    'beauty.searchServices': 'ค้นหาบริการ...',
    'beauty.bookAppointment': 'นัดหมาย',
    'beauty.selectDate': 'เลือกวันที่',
    'beauty.selectTime': 'เลือกเวลา',
    'beauty.contactInfo': 'ข้อมูลติดต่อ',
    'beauty.confirmBooking': 'ยืนยันการจอง',
    'beauty.bookingSuccess': 'จองสำเร็จ!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('uno-language');
    return (saved as Language) || 'ru';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('uno-language', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
