import { normalizeFurnishingLevel, normalizeViewTypes } from '@/lib/propertyFormNormalizers';
import type { AssetClass, OwnershipData, PropertyFormData } from './types';

export const initialFormData: PropertyFormData = {
  asset_class: 'residential',
  title: '',
  title_ru: '',
  internal_name: '',
  address: '',
  district: '',
  lat: undefined,
  lng: undefined,
  property_type: 'apartment',
  bedrooms: 1,
  bathrooms: 1,
  area_sqm: '',
  description: '',
  description_ru: '',
  cover_image: '',
  images: [],
  management_type: 'full',
  is_rented: false,
  rental_platforms: [],
  custom_platform: '',
  project_id: undefined,
  complex_id: undefined,
  video_url: '',
  floor: undefined,
  unit_number: '',
  total_floors: undefined,
  plot_size_sqm: undefined,
  has_elevator: false,
  parking_type: '',
  pool_type: '',
  garden_type: '',
  view_type: [],
  furnishing_level: '',
  equipment: [],
  price_per_night: '',
  min_stay_nights: 1,
  max_guests: 2,
  deposit_amount: '',
  check_in_time: '14:00',
  check_out_time: '12:00',
  instant_booking: false,
  ownership_form: undefined,
  is_for_sale: false,
  sale_price: '',
  pets_allowed: false,
  smoking_allowed: false,
  parties_allowed: false,
  children_friendly: true,
  quiet_hours_start: '22:00',
  quiet_hours_end: '08:00',
  cancellation_policy: 'flexible',
  seasonal_pricing: [],
  highlights: [],
  platform_listed: true,
  payment_policy: 'prepay_10',
  deposit_currency: 'USD',
  negotiation_enabled: false,
  lock_code: '',
  tenancy_modes: [],
  deposit_months_long: 2,
  advance_months_long: 1,
  utilities_included_long: [],
  tm30_registration_supported: false,
  is_assignment: false,
  is_quick_sale: false,
  accepts_installments: false,
  escrow_offered: false,
  encumbrances_disclosed: false,
  installment_plan: [],
};

export const initialOwnershipData: OwnershipData = {
  ownership_type: 'own',
  actual_owner_email: '',
  actual_owner_name: '',
  actual_owner_phone: '',
  send_invite_immediately: true,
  management_document_url: '',
  management_document_name: '',
  commercial_terms_redacted: false,
  ownership_document_url: '',
  ownership_document_name: '',
};

export function mapPropertyToFormData(property: any): PropertyFormData {
  return {
    asset_class: (property.asset_class as AssetClass) || 'residential',
    title: property.title_en || property.title || '',
    title_ru: property.title_ru || '',
    internal_name: property.internal_name || '',
    address: property.address || '',
    district: property.district || '',
    lat: property.lat ?? undefined,
    lng: property.lng ?? undefined,
    property_type: property.property_type || 'apartment',
    bedrooms: property.bedrooms || 1,
    bathrooms: property.bathrooms || 1,
    area_sqm: property.area_sqm?.toString() || '',
    description: property.description_en || '',
    description_ru: property.description_ru || '',
    cover_image: property.cover_image || '',
    images: property.images || [],
    management_type: property.management_type || 'full',
    is_rented: property.is_rented || false,
    rental_platforms: property.rental_platform ? [property.rental_platform] : [],
    custom_platform: '',
    project_id: property.project_id ?? undefined,
    complex_id: property.complex_id ?? undefined,
    video_url: property.video_url || '',
    floor: property.floor ?? undefined,
    unit_number: property.unit_number || '',
    total_floors: property.total_floors ?? undefined,
    plot_size_sqm: property.plot_size_sqm ?? undefined,
    has_elevator: property.has_elevator || false,
    parking_type: property.parking_type || '',
    pool_type: property.pool_type || '',
    garden_type: property.garden_type || '',
    view_type: normalizeViewTypes(property.view_type),
    furnishing_level: normalizeFurnishingLevel(property.furnishing_level),
    equipment: property.equipment || [],
    price_per_night: property.price_per_night ? String(property.price_per_night) : '',
    min_stay_nights: property.min_stay_nights || 1,
    max_guests: property.max_guests || 2,
    deposit_amount: property.deposit_amount ? String(property.deposit_amount) : '',
    check_in_time: property.check_in_time || '14:00',
    check_out_time: property.check_out_time || '12:00',
    instant_booking: property.instant_booking || false,
    ownership_form: property.ownership_form || undefined,
    is_for_sale: property.is_for_sale || false,
    sale_price: property.sale_price ? String(property.sale_price) : '',
    pets_allowed: property.pets_allowed || false,
    pet_deposit: property.pet_deposit ?? undefined,
    smoking_allowed: property.smoking_policy === 'allowed' || property.smoking_allowed || false,
    smoking_penalty: property.smoking_penalty ?? undefined,
    parties_allowed: property.parties_allowed || false,
    max_party_guests: property.max_party_guests ?? undefined,
    children_friendly: property.children_friendly ?? true,
    has_crib: property.has_crib || false,
    has_high_chair: property.has_high_chair || false,
    quiet_hours_start: property.quiet_hours_start || '22:00',
    quiet_hours_end: property.quiet_hours_end || '08:00',
    house_rules: property.house_rules || '',
    house_rules_ru: property.house_rules_ru || '',
    cancellation_policy: property.cancellation_policy || 'flexible',
    weekly_discount: property.weekly_discount || 0,
    monthly_discount: property.monthly_discount || 0,
    seasonal_pricing: property.seasonal_pricing || [],
    highlights: property.highlights || [],
    platform_listed: property.listing_modes?.includes('platform') ?? false,
    early_booking_discount: property.early_booking_discount ?? undefined,
    early_booking_days: property.early_booking_days ?? undefined,
    last_minute_discount: property.last_minute_discount ?? undefined,
    last_minute_days: property.last_minute_days ?? undefined,
    payment_policy: property.payment_policy || 'prepay_10',
    prepay_percent: property.prepay_percent ?? undefined,
    balance_due_days: property.balance_due_days ?? undefined,
    deposit_currency: property.deposit_currency || 'USD',
    negotiation_enabled: property.negotiation_enabled || false,
    custom_length_discounts: property.custom_length_discounts || [],
    lock_code: property.lock_code || '',
    floor_area_sqm: property.floor_area_sqm ?? undefined,
    cap_rate_pct: property.cap_rate_pct ?? undefined,
    noi_annual_thb: property.noi_annual_thb ?? undefined,
    zoning: property.zoning || undefined,
    title_deed_type: property.title_deed_type || undefined,
    permitted_uses: property.permitted_uses || undefined,
    electricity_load_kw: property.electricity_load_kw ?? undefined,
    land_size_sqm: property.land_size_sqm ?? undefined,
    land_size_rai: property.land_size_rai ?? undefined,
    frontage_m: property.frontage_m ?? undefined,
    tenancy_modes: Array.isArray(property.tenancy_modes) ? property.tenancy_modes : [],
    price_per_month: property.price_per_month != null ? String(property.price_per_month) : '',
    price_per_year: property.price_per_year != null ? String(property.price_per_year) : '',
    deposit_months_long: property.deposit_months_long ?? 2,
    advance_months_long: property.advance_months_long ?? 1,
    min_lease_months: property.min_lease_months ?? undefined,
    utilities_included_long: property.utilities_included_long || [],
    tm30_registration_supported: property.tm30_registration_supported ?? false,
    sale_intent: property.sale_intent ?? undefined,
    is_assignment: property.is_assignment ?? false,
    assignment_premium: property.assignment_premium != null ? String(property.assignment_premium) : '',
    original_contract_price: property.original_contract_price != null ? String(property.original_contract_price) : '',
    remaining_to_developer: property.remaining_to_developer != null ? String(property.remaining_to_developer) : '',
    spa_stage: property.spa_stage ?? undefined,
    transfer_fee_split: property.transfer_fee_split ?? undefined,
    is_quick_sale: property.is_quick_sale ?? false,
    quick_sale_reason: property.quick_sale_reason ?? undefined,
    quick_sale_discount_pct: property.quick_sale_discount_pct ?? undefined,
    urgency_deadline: property.urgency_deadline ?? undefined,
    accepts_installments: property.accepts_installments ?? false,
    installment_plan: Array.isArray(property.installment_plan) ? property.installment_plan : [],
    escrow_offered: property.escrow_offered ?? false,
    escrow_provider: property.escrow_provider ?? undefined,
    title_deed_url: property.title_deed_url || '',
    encumbrances_disclosed: property.encumbrances_disclosed ?? false,
    encumbrances_description: property.encumbrances_description || '',
    foreign_quota_available: property.foreign_quota_available ?? undefined,
    video_file_url: property.video_file_url || '',
    virtual_tour_url: property.virtual_tour_url || '',
  };
}
