// This file is auto-generated by Lovable. Do not modify it.
// MANUAL OVERRIDE: oauthBrokerUrl is set to the absolute Lovable broker URL
// because the default relative path "/~oauth/initiate" only resolves on
// Lovable-hosted previews. On Vercel (myuno.app) it 404s into the SPA.
// If Lovable regenerates this file, re-apply the createLovableAuth config.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth({
  oauthBrokerUrl: "https://oauth.lovable.app/~oauth/initiate",
});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
