import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// All intake verticals - migrated from intakeVerticals.ts
const INTAKE_VERTICALS = [
  {
    vertical_id: 'yachts',
    target_table: 'yachts',
    name_en: 'Yachts',
    name_ru: 'Яхты',
    icon: '🚤',
    keywords: ['yacht', 'яхта', 'boat', 'лодка', 'катер', 'charter', 'чартер', 'vessel', 'судно', 'катамаран', 'catamaran', 'sailboat', 'парусник'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'price_per_day', 'price_per_hour', 'capacity', 'length', 'year', 'yacht_type', 'cover_image', 'images', 'features', 'crew_size'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      name_ru: { en: 'Name (RU)', ru: 'Название (RU)', type: 'string' },
      description_en: { en: 'Description (EN)', ru: 'Описание (EN)', type: 'string' },
      description_ru: { en: 'Description (RU)', ru: 'Описание (RU)', type: 'string' },
      price_per_day: { en: 'Price per Day', ru: 'Цена за день', type: 'number' },
      price_per_hour: { en: 'Price per Hour', ru: 'Цена за час', type: 'number' },
      capacity: { en: 'Capacity', ru: 'Вместимость', type: 'number' },
      length: { en: 'Length (m)', ru: 'Длина (м)', type: 'number' },
      year: { en: 'Year Built', ru: 'Год постройки', type: 'number' },
      yacht_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['motor', 'sailing', 'catamaran', 'speedboat'] },
      crew_size: { en: 'Crew Size', ru: 'Размер экипажа', type: 'number' },
      features: { en: 'Features', ru: 'Удобства', type: 'array' },
      cover_image: { en: 'Cover Image', ru: 'Главное фото', type: 'string' },
      images: { en: 'Gallery', ru: 'Галерея', type: 'array' },
    },
    sort_order: 1,
  },
  {
    vertical_id: 'properties',
    target_table: 'properties',
    name_en: 'Properties',
    name_ru: 'Недвижимость',
    icon: '🏠',
    keywords: ['property', 'недвижимость', 'квартира', 'apartment', 'villa', 'вилла', 'condo', 'кондо', 'house', 'дом', 'rent', 'аренда', 'studio', 'студия', 'penthouse', 'пентхаус'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'price_per_month', 'price_per_day', 'bedrooms', 'bathrooms', 'area_sqm', 'district', 'address', 'property_type', 'cover_image', 'images', 'amenities', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Title (EN)', ru: 'Название (EN)', type: 'string' },
      name_ru: { en: 'Title (RU)', ru: 'Название (RU)', type: 'string' },
      price_per_month: { en: 'Price/Month', ru: 'Цена/месяц', type: 'number' },
      price_per_day: { en: 'Price/Day', ru: 'Цена/день', type: 'number' },
      bedrooms: { en: 'Bedrooms', ru: 'Спален', type: 'number' },
      bathrooms: { en: 'Bathrooms', ru: 'Ванных', type: 'number' },
      area_sqm: { en: 'Area (sqm)', ru: 'Площадь (м²)', type: 'number' },
      district: { en: 'District', ru: 'Район', type: 'string' },
      property_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['apartment', 'villa', 'condo', 'house', 'studio', 'penthouse'] },
    },
    sort_order: 2,
  },
  {
    vertical_id: 'owner_properties',
    target_table: 'owner_properties',
    name_en: 'Owner Properties',
    name_ru: 'Объекты собственников',
    icon: '🏡',
    keywords: ['owner property', 'собственник', 'владелец', 'сдаю', 'my property', 'моя квартира', 'моя вилла'],
    required_fields: ['title_en'],
    optional_fields: ['title_ru', 'description_en', 'description_ru', 'monthly_rent', 'daily_rate', 'bedrooms', 'bathrooms', 'area_sqm', 'district', 'address', 'property_type', 'cover_image', 'images', 'amenities'],
    field_labels: {
      title_en: { en: 'Title (EN)', ru: 'Название (EN)', type: 'string' },
      title_ru: { en: 'Title (RU)', ru: 'Название (RU)', type: 'string' },
      monthly_rent: { en: 'Monthly Rent', ru: 'Месячная аренда', type: 'number' },
      daily_rate: { en: 'Daily Rate', ru: 'Дневная ставка', type: 'number' },
    },
    sort_order: 3,
  },
  {
    vertical_id: 'tours',
    target_table: 'tours',
    name_en: 'Tours',
    name_ru: 'Туры',
    icon: '🗺️',
    keywords: ['tour', 'тур', 'excursion', 'экскурсия', 'trip', 'поездка', 'island hopping', 'островной тур', 'sightseeing', 'обзорная'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'price', 'duration_hours', 'tour_type', 'max_participants', 'included', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      price: { en: 'Price', ru: 'Цена', type: 'number' },
      duration_hours: { en: 'Duration (hours)', ru: 'Длительность (часы)', type: 'number' },
      tour_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['island', 'city', 'adventure', 'cultural', 'food', 'nature'] },
    },
    sort_order: 4,
  },
  {
    vertical_id: 'water_activities',
    target_table: 'water_activities',
    name_en: 'Water Activities',
    name_ru: 'Водные развлечения',
    icon: '🏄',
    keywords: ['diving', 'дайвинг', 'snorkeling', 'сноркелинг', 'jet ski', 'гидроцикл', 'parasailing', 'парасейлинг', 'kayak', 'каяк', 'surfing', 'сёрфинг', 'wakeboard', 'вейкборд', 'water sport', 'водный спорт'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'price', 'duration_minutes', 'activity_type', 'difficulty', 'min_age', 'equipment_included', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      price: { en: 'Price', ru: 'Цена', type: 'number' },
      activity_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['diving', 'snorkeling', 'jet_ski', 'parasailing', 'kayak', 'surfing', 'wakeboard'] },
      difficulty: { en: 'Difficulty', ru: 'Сложность', type: 'string', enumValues: ['beginner', 'intermediate', 'advanced'] },
    },
    sort_order: 5,
  },
  {
    vertical_id: 'restaurants',
    target_table: 'restaurants',
    name_en: 'Restaurants',
    name_ru: 'Рестораны',
    icon: '🍽️',
    keywords: ['restaurant', 'ресторан', 'cafe', 'кафе', 'bar', 'бар', 'bistro', 'бистро', 'food', 'еда', 'cuisine', 'кухня', 'menu', 'меню', 'dining'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'cuisine_type', 'price_range', 'address', 'district', 'phone', 'website', 'working_hours', 'features', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      cuisine_type: { en: 'Cuisine', ru: 'Кухня', type: 'array' },
      price_range: { en: 'Price Range', ru: 'Ценовая категория', type: 'string', enumValues: ['$', '$$', '$$$', '$$$$'] },
    },
    sort_order: 6,
  },
  {
    vertical_id: 'salons',
    target_table: 'salons',
    name_en: 'Beauty Salons',
    name_ru: 'Салоны красоты',
    icon: '💇',
    keywords: ['salon', 'салон', 'spa', 'спа', 'beauty', 'красота', 'massage', 'массаж', 'manicure', 'маникюр', 'pedicure', 'педикюр', 'hair', 'волосы', 'nails', 'ногти'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'salon_type', 'services', 'price_from', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      salon_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['beauty', 'spa', 'nails', 'hair', 'massage'] },
    },
    sort_order: 7,
  },
  {
    vertical_id: 'clinics',
    target_table: 'clinics',
    name_en: 'Clinics',
    name_ru: 'Клиники',
    icon: '🏥',
    keywords: ['clinic', 'клиника', 'hospital', 'госпиталь', 'doctor', 'доктор', 'врач', 'medical', 'медицинский', 'dental', 'стоматология', 'health', 'здоровье'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'clinic_type', 'specialty', 'consultation_price', 'address', 'district', 'phone', 'email', 'website', 'working_hours', 'languages', 'is_24h', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      clinic_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['general', 'dental', 'dermatology', 'ophthalmology', 'pediatric', 'veterinary'] },
    },
    sort_order: 8,
  },
  {
    vertical_id: 'gyms',
    target_table: 'gyms',
    name_en: 'Fitness',
    name_ru: 'Фитнес',
    icon: '🏋️',
    keywords: ['gym', 'зал', 'fitness', 'фитнес', 'workout', 'тренировка', 'crossfit', 'кроссфит', 'yoga', 'йога', 'pilates', 'пилатес', 'sport', 'спорт'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'gym_type', 'price_per_day', 'price_per_month', 'amenities', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      gym_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['gym', 'crossfit', 'yoga', 'pilates', 'martial_arts', 'swimming'] },
    },
    sort_order: 9,
  },
  {
    vertical_id: 'vehicles',
    target_table: 'vehicles',
    name_en: 'Transport',
    name_ru: 'Транспорт',
    icon: '🚗',
    keywords: ['car', 'машина', 'авто', 'auto', 'motorbike', 'мотобайк', 'scooter', 'скутер', 'bike', 'велосипед', 'rental', 'прокат', 'vehicle', 'транспорт'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'vehicle_type', 'brand', 'model', 'year', 'price_per_day', 'deposit', 'features', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      vehicle_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['car', 'motorbike', 'scooter', 'bicycle', 'atv'] },
      price_per_day: { en: 'Price/Day', ru: 'Цена/день', type: 'number' },
    },
    sort_order: 10,
  },
  {
    vertical_id: 'events',
    target_table: 'events',
    name_en: 'Events',
    name_ru: 'События',
    icon: '🎉',
    keywords: ['event', 'событие', 'party', 'вечеринка', 'concert', 'концерт', 'festival', 'фестиваль', 'show', 'шоу', 'exhibition', 'выставка'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'event_type', 'event_date', 'start_time', 'end_time', 'venue', 'address', 'price', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      event_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['party', 'concert', 'festival', 'exhibition', 'sports', 'workshop'] },
      event_date: { en: 'Date', ru: 'Дата', type: 'date' },
    },
    sort_order: 11,
  },
  {
    vertical_id: 'babysitters',
    target_table: 'babysitters',
    name_en: 'Babysitters',
    name_ru: 'Няни',
    icon: '👶',
    keywords: ['babysitter', 'няня', 'nanny', 'childcare', 'присмотр за детьми', 'baby', 'ребёнок', 'children', 'дети'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'bio_en', 'bio_ru', 'experience_years', 'age_groups', 'languages', 'price_per_hour', 'price_per_day', 'certifications', 'first_aid_certified', 'can_drive', 'can_cook', 'photo', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Имя (EN)', type: 'string' },
      experience_years: { en: 'Experience (years)', ru: 'Опыт (лет)', type: 'number' },
      price_per_hour: { en: 'Price/Hour', ru: 'Цена/час', type: 'number' },
    },
    sort_order: 12,
  },
  {
    vertical_id: 'cleaning_services',
    target_table: 'cleaning_services',
    name_en: 'Cleaning',
    name_ru: 'Уборка',
    icon: '🧹',
    keywords: ['cleaning', 'уборка', 'maid', 'горничная', 'housekeeping', 'клининг', 'deep clean', 'генеральная уборка'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'service_type', 'price_per_hour', 'price_fixed', 'duration_hours', 'areas_served', 'features', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      service_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['regular', 'deep', 'move_in', 'move_out', 'post_construction'] },
    },
    sort_order: 13,
  },
  {
    vertical_id: 'legal_services',
    target_table: 'legal_services',
    name_en: 'Legal Services',
    name_ru: 'Юридические услуги',
    icon: '⚖️',
    keywords: ['lawyer', 'юрист', 'адвокат', 'legal', 'юридический', 'visa', 'виза', 'immigration', 'иммиграция', 'notary', 'нотариус', 'contract', 'договор'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'service_type', 'specialization', 'price_from', 'consultation_price', 'languages', 'address', 'phone', 'email', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      service_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['visa', 'immigration', 'business', 'real_estate', 'criminal', 'family'] },
    },
    sort_order: 14,
  },
  {
    vertical_id: 'pet_services',
    target_table: 'pet_services',
    name_en: 'Pet Services',
    name_ru: 'Услуги для питомцев',
    icon: '🐕',
    keywords: ['pet', 'питомец', 'dog', 'собака', 'cat', 'кошка', 'vet', 'ветеринар', 'grooming', 'груминг', 'pet sitting', 'передержка', 'walking', 'выгул'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'service_type', 'pet_types', 'price_per_visit', 'price_per_day', 'address', 'phone', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      service_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['veterinary', 'grooming', 'sitting', 'walking', 'training', 'boarding'] },
    },
    sort_order: 15,
  },
  {
    vertical_id: 'education_providers',
    target_table: 'education_providers',
    name_en: 'Education',
    name_ru: 'Образование',
    icon: '🎓',
    keywords: ['school', 'школа', 'education', 'образование', 'course', 'курс', 'tutor', 'репетитор', 'language', 'язык', 'training', 'обучение', 'lesson', 'урок'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'education_type', 'subjects', 'age_groups', 'price_per_lesson', 'price_per_month', 'languages', 'address', 'phone', 'website', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      education_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['language', 'academic', 'professional', 'arts', 'sports', 'music'] },
    },
    sort_order: 16,
  },
  {
    vertical_id: 'pharmacies',
    target_table: 'pharmacies',
    name_en: 'Pharmacies',
    name_ru: 'Аптеки',
    icon: '💊',
    keywords: ['pharmacy', 'аптека', 'medicine', 'лекарство', 'drug', 'препарат', 'drugstore', 'medical supplies', 'медикаменты'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'is_24h', 'has_delivery', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      is_24h: { en: '24 Hours', ru: 'Круглосуточно', type: 'boolean' },
    },
    sort_order: 17,
  },
  {
    vertical_id: 'insurance_providers',
    target_table: 'insurance_providers',
    name_en: 'Insurance',
    name_ru: 'Страхование',
    icon: '🛡️',
    keywords: ['insurance', 'страховка', 'страхование', 'policy', 'полис', 'health insurance', 'медстраховка', 'travel insurance', 'туристическая страховка'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'insurance_types', 'price_from', 'languages', 'address', 'phone', 'email', 'website', 'cover_image', 'images'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
    },
    sort_order: 18,
  },
  {
    vertical_id: 'flower_shops',
    target_table: 'flower_shops',
    name_en: 'Flower Shops',
    name_ru: 'Цветочные магазины',
    icon: '💐',
    keywords: ['flowers', 'цветы', 'bouquet', 'букет', 'florist', 'флорист', 'roses', 'розы', 'delivery', 'доставка цветов'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'has_delivery', 'delivery_areas', 'price_from', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
    },
    sort_order: 19,
  },
  {
    vertical_id: 'stores',
    target_table: 'stores',
    name_en: 'Stores',
    name_ru: 'Магазины',
    icon: '🏪',
    keywords: ['store', 'магазин', 'shop', 'shopping', 'retail', 'розница', 'supermarket', 'супермаркет', 'grocery', 'продукты'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'store_type', 'categories', 'has_delivery', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      store_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['supermarket', 'convenience', 'specialty', 'electronics', 'clothing'] },
    },
    sort_order: 20,
  },
  {
    vertical_id: 'coworking',
    target_table: 'coworking',
    name_en: 'Coworking',
    name_ru: 'Коворкинг',
    icon: '💻',
    keywords: ['coworking', 'коворкинг', 'office', 'офис', 'workspace', 'рабочее место', 'remote work', 'удалёнка', 'hot desk', 'meeting room'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'price_per_day', 'price_per_month', 'amenities', 'address', 'district', 'phone', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      price_per_day: { en: 'Day Pass', ru: 'Дневной абонемент', type: 'number' },
      price_per_month: { en: 'Monthly', ru: 'Месячный', type: 'number' },
    },
    sort_order: 21,
  },
  {
    vertical_id: 'banks',
    target_table: 'banks',
    name_en: 'Banks',
    name_ru: 'Банки',
    icon: '🏦',
    keywords: ['bank', 'банк', 'banking', 'банковский', 'account', 'счёт', 'transfer', 'перевод', 'atm', 'банкомат', 'currency exchange', 'обмен валют'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'bank_type', 'services', 'accepts_foreigners', 'languages', 'address', 'district', 'phone', 'website', 'working_hours', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      accepts_foreigners: { en: 'For Foreigners', ru: 'Для иностранцев', type: 'boolean' },
    },
    sort_order: 22,
  },
  {
    vertical_id: 'attractions',
    target_table: 'attractions',
    name_en: 'Attractions',
    name_ru: 'Достопримечательности',
    icon: '🎢',
    keywords: ['attraction', 'достопримечательность', 'temple', 'храм', 'viewpoint', 'смотровая', 'beach', 'пляж', 'waterfall', 'водопад', 'national park', 'национальный парк'],
    required_fields: ['name_en'],
    optional_fields: ['name_ru', 'description_en', 'description_ru', 'attraction_type', 'entry_fee', 'opening_hours', 'address', 'district', 'phone', 'website', 'cover_image', 'images', 'lat', 'lng'],
    field_labels: {
      name_en: { en: 'Name (EN)', ru: 'Название (EN)', type: 'string' },
      attraction_type: { en: 'Type', ru: 'Тип', type: 'string', enumValues: ['temple', 'beach', 'viewpoint', 'waterfall', 'park', 'museum', 'market'] },
      entry_fee: { en: 'Entry Fee', ru: 'Входная плата', type: 'number' },
    },
    sort_order: 23,
  },
];

// Lead verticals for Universal Lead Form
const LEAD_VERTICALS = [
  {
    vertical_id: 'properties',
    icon: '🏠',
    name_en: 'Property',
    name_ru: 'Недвижимость',
    short_desc_en: 'Rent or buy property',
    short_desc_ru: 'Аренда или покупка',
    cta_text_en: 'Find Property',
    cta_text_ru: 'Найти жильё',
    popularity_score: 100,
    request_types: [
      { value: 'vacation_rental', labelEn: 'Vacation Rental', labelRu: 'Аренда на отпуск' },
      { value: 'long_term_rental', labelEn: 'Long-term Rental', labelRu: 'Долгосрочная аренда' },
      { value: 'property_purchase', labelEn: 'Purchase', labelRu: 'Покупка' },
      { value: 'property_tour', labelEn: 'Property Tour', labelRu: 'Тур по объектам' },
      { value: 'investment_advice', labelEn: 'Investment Advice', labelRu: 'Инвестиции' },
    ],
    fields: [
      { key: 'dates', type: 'daterange', labelEn: 'Dates', labelRu: 'Даты', required: true },
      { key: 'guests', type: 'guests', labelEn: 'Guests', labelRu: 'Гости', required: true },
      { key: 'property_type', type: 'multiselect', labelEn: 'Property Type', labelRu: 'Тип недвижимости', options: [
        { value: 'villa', labelEn: 'Villa', labelRu: 'Вилла' },
        { value: 'condo', labelEn: 'Condo', labelRu: 'Кондо' },
        { value: 'apartment', labelEn: 'Apartment', labelRu: 'Апартаменты' },
        { value: 'townhouse', labelEn: 'Townhouse', labelRu: 'Таунхаус' },
      ]},
      { key: 'budget', type: 'budget', labelEn: 'Budget', labelRu: 'Бюджет', required: false },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 1,
  },
  {
    vertical_id: 'yachts',
    icon: '🚤',
    name_en: 'Yachts',
    name_ru: 'Яхты',
    short_desc_en: 'Charter a yacht',
    short_desc_ru: 'Арендовать яхту',
    cta_text_en: 'Charter Yacht',
    cta_text_ru: 'Арендовать яхту',
    popularity_score: 90,
    request_types: [
      { value: 'yacht_charter', labelEn: 'Day Charter', labelRu: 'Дневной чартер' },
      { value: 'yacht_multiday', labelEn: 'Multi-day Charter', labelRu: 'Многодневный чартер' },
      { value: 'yacht_party', labelEn: 'Yacht Party', labelRu: 'Вечеринка на яхте' },
      { value: 'yacht_purchase', labelEn: 'Purchase Yacht', labelRu: 'Покупка яхты' },
    ],
    fields: [
      { key: 'charter_date', type: 'date', labelEn: 'Charter Date', labelRu: 'Дата аренды', required: true },
      { key: 'duration', type: 'select', labelEn: 'Duration', labelRu: 'Продолжительность', required: true, options: [
        { value: 'half_day', labelEn: 'Half Day (4h)', labelRu: 'Полдня (4ч)' },
        { value: 'full_day', labelEn: 'Full Day (8h)', labelRu: 'Целый день (8ч)' },
        { value: 'sunset', labelEn: 'Sunset Cruise (3h)', labelRu: 'Закатный круиз (3ч)' },
        { value: 'overnight', labelEn: 'Overnight', labelRu: 'С ночёвкой' },
        { value: 'multiday', labelEn: 'Multi-day', labelRu: 'Несколько дней' },
      ]},
      { key: 'guests', type: 'guests', labelEn: 'Guests', labelRu: 'Гости', required: true },
      { key: 'budget', type: 'budget', labelEn: 'Budget', labelRu: 'Бюджет', required: false },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 2,
  },
  {
    vertical_id: 'tours',
    icon: '🗺️',
    name_en: 'Tours',
    name_ru: 'Туры',
    short_desc_en: 'Book an excursion',
    short_desc_ru: 'Забронировать экскурсию',
    cta_text_en: 'Book Tour',
    cta_text_ru: 'Забронировать тур',
    popularity_score: 85,
    request_types: [
      { value: 'island_tour', labelEn: 'Island Tour', labelRu: 'Островной тур' },
      { value: 'city_tour', labelEn: 'City Tour', labelRu: 'Обзорная экскурсия' },
      { value: 'adventure_tour', labelEn: 'Adventure', labelRu: 'Приключения' },
      { value: 'custom_tour', labelEn: 'Custom Tour', labelRu: 'Индивидуальный тур' },
    ],
    fields: [
      { key: 'tour_date', type: 'date', labelEn: 'Tour Date', labelRu: 'Дата тура', required: true },
      { key: 'guests', type: 'guests', labelEn: 'Guests', labelRu: 'Гости', required: true },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 3,
  },
  {
    vertical_id: 'vehicles',
    icon: '🚗',
    name_en: 'Transport',
    name_ru: 'Транспорт',
    short_desc_en: 'Rent a car or bike',
    short_desc_ru: 'Аренда авто или байка',
    cta_text_en: 'Rent Vehicle',
    cta_text_ru: 'Арендовать транспорт',
    popularity_score: 80,
    request_types: [
      { value: 'car_rental', labelEn: 'Car Rental', labelRu: 'Аренда автомобиля' },
      { value: 'bike_rental', labelEn: 'Motorbike Rental', labelRu: 'Аренда мотобайка' },
      { value: 'driver_service', labelEn: 'Driver Service', labelRu: 'Водитель с авто' },
      { value: 'airport_transfer', labelEn: 'Airport Transfer', labelRu: 'Трансфер из аэропорта' },
    ],
    fields: [
      { key: 'dates', type: 'daterange', labelEn: 'Dates', labelRu: 'Даты', required: true },
      { key: 'vehicle_type', type: 'select', labelEn: 'Vehicle Type', labelRu: 'Тип транспорта', required: true, options: [
        { value: 'car', labelEn: 'Car', labelRu: 'Автомобиль' },
        { value: 'suv', labelEn: 'SUV', labelRu: 'Внедорожник' },
        { value: 'motorbike', labelEn: 'Motorbike', labelRu: 'Мотобайк' },
        { value: 'scooter', labelEn: 'Scooter', labelRu: 'Скутер' },
      ]},
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 4,
  },
  {
    vertical_id: 'legal',
    icon: '⚖️',
    name_en: 'Legal',
    name_ru: 'Юридические услуги',
    short_desc_en: 'Legal consultation',
    short_desc_ru: 'Юридическая консультация',
    cta_text_en: 'Get Consultation',
    cta_text_ru: 'Получить консультацию',
    popularity_score: 60,
    request_types: [
      { value: 'visa_consultation', labelEn: 'Visa & Immigration', labelRu: 'Виза и иммиграция' },
      { value: 'property_legal', labelEn: 'Property Legal', labelRu: 'Недвижимость' },
      { value: 'business_legal', labelEn: 'Business Setup', labelRu: 'Открытие бизнеса' },
      { value: 'general_legal', labelEn: 'General Consultation', labelRu: 'Общая консультация' },
    ],
    fields: [
      { key: 'legal_topic', type: 'select', labelEn: 'Topic', labelRu: 'Тема консультации', required: true, options: [
        { value: 'visa', labelEn: 'Visa Extension', labelRu: 'Продление визы' },
        { value: 'elite_visa', labelEn: 'Thailand Elite Visa', labelRu: 'Thailand Elite виза' },
        { value: 'work_permit', labelEn: 'Work Permit', labelRu: 'Разрешение на работу' },
        { value: 'company', labelEn: 'Company Registration', labelRu: 'Регистрация компании' },
        { value: 'property', labelEn: 'Property Purchase', labelRu: 'Покупка недвижимости' },
        { value: 'other', labelEn: 'Other', labelRu: 'Другое' },
      ]},
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 5,
  },
  {
    vertical_id: 'clinics',
    icon: '🏥',
    name_en: 'Medical',
    name_ru: 'Медицина',
    short_desc_en: 'Find a doctor',
    short_desc_ru: 'Найти врача',
    cta_text_en: 'Find Doctor',
    cta_text_ru: 'Найти врача',
    popularity_score: 55,
    request_types: [
      { value: 'doctor_appointment', labelEn: 'Doctor Appointment', labelRu: 'Запись к врачу' },
      { value: 'dental', labelEn: 'Dental', labelRu: 'Стоматология' },
      { value: 'health_checkup', labelEn: 'Health Checkup', labelRu: 'Чек-ап' },
      { value: 'emergency', labelEn: 'Emergency Help', labelRu: 'Срочная помощь' },
    ],
    fields: [
      { key: 'medical_type', type: 'select', labelEn: 'Service Type', labelRu: 'Тип услуги', required: true, options: [
        { value: 'general', labelEn: 'General Doctor', labelRu: 'Терапевт' },
        { value: 'dental', labelEn: 'Dentist', labelRu: 'Стоматолог' },
        { value: 'dermatology', labelEn: 'Dermatologist', labelRu: 'Дерматолог' },
        { value: 'pediatric', labelEn: 'Pediatrician', labelRu: 'Педиатр' },
        { value: 'checkup', labelEn: 'Full Checkup', labelRu: 'Полный чек-ап' },
        { value: 'other', labelEn: 'Other', labelRu: 'Другое' },
      ]},
      { key: 'preferred_date', type: 'date', labelEn: 'Preferred Date', labelRu: 'Предпочтительная дата' },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 6,
  },
  {
    vertical_id: 'babysitters',
    icon: '👶',
    name_en: 'Babysitters',
    name_ru: 'Няни',
    short_desc_en: 'Find a babysitter',
    short_desc_ru: 'Найти няню',
    cta_text_en: 'Find Babysitter',
    cta_text_ru: 'Найти няню',
    popularity_score: 50,
    request_types: [
      { value: 'babysitter_hourly', labelEn: 'Hourly Babysitting', labelRu: 'Почасовая няня' },
      { value: 'babysitter_daily', labelEn: 'Full Day', labelRu: 'На весь день' },
      { value: 'nanny_longterm', labelEn: 'Long-term Nanny', labelRu: 'Няня на длительный срок' },
    ],
    fields: [
      { key: 'children_ages', type: 'text', labelEn: 'Children Ages', labelRu: 'Возраст детей', placeholderEn: 'e.g., 2 and 5 years old', placeholderRu: 'Напр., 2 и 5 лет', required: true },
      { key: 'dates', type: 'daterange', labelEn: 'Dates', labelRu: 'Даты', required: true },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 7,
  },
  {
    vertical_id: 'salons',
    icon: '💇',
    name_en: 'Beauty & Spa',
    name_ru: 'Красота и Spa',
    short_desc_en: 'Book beauty services',
    short_desc_ru: 'Записаться на услуги',
    cta_text_en: 'Book Service',
    cta_text_ru: 'Записаться',
    popularity_score: 45,
    request_types: [
      { value: 'spa_booking', labelEn: 'Spa & Massage', labelRu: 'Спа и массаж' },
      { value: 'hair_salon', labelEn: 'Hair Salon', labelRu: 'Парикмахерская' },
      { value: 'nail_salon', labelEn: 'Nail Salon', labelRu: 'Маникюр/Педикюр' },
      { value: 'beauty_service', labelEn: 'Beauty Service', labelRu: 'Бьюти-услуги' },
    ],
    fields: [
      { key: 'service_type', type: 'select', labelEn: 'Service', labelRu: 'Услуга', required: true, options: [
        { value: 'massage', labelEn: 'Massage', labelRu: 'Массаж' },
        { value: 'spa', labelEn: 'Spa Package', labelRu: 'Спа-программа' },
        { value: 'hair', labelEn: 'Haircut/Styling', labelRu: 'Стрижка/Укладка' },
        { value: 'nails', labelEn: 'Manicure/Pedicure', labelRu: 'Маникюр/Педикюр' },
        { value: 'facial', labelEn: 'Facial', labelRu: 'Уход за лицом' },
        { value: 'other', labelEn: 'Other', labelRu: 'Другое' },
      ]},
      { key: 'preferred_date', type: 'date', labelEn: 'Preferred Date', labelRu: 'Предпочтительная дата' },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 8,
  },
  {
    vertical_id: 'gyms',
    icon: '🏋️',
    name_en: 'Fitness',
    name_ru: 'Фитнес',
    short_desc_en: 'Find a gym or trainer',
    short_desc_ru: 'Найти зал или тренера',
    cta_text_en: 'Find Gym',
    cta_text_ru: 'Найти зал',
    popularity_score: 40,
    request_types: [
      { value: 'gym_daypass', labelEn: 'Day Pass', labelRu: 'Дневной абонемент' },
      { value: 'gym_membership', labelEn: 'Membership', labelRu: 'Абонемент' },
      { value: 'personal_trainer', labelEn: 'Personal Trainer', labelRu: 'Персональный тренер' },
      { value: 'yoga_class', labelEn: 'Yoga/Pilates', labelRu: 'Йога/Пилатес' },
    ],
    fields: [
      { key: 'fitness_type', type: 'select', labelEn: 'Activity Type', labelRu: 'Тип активности', required: true, options: [
        { value: 'gym', labelEn: 'Gym/Fitness', labelRu: 'Зал/Фитнес' },
        { value: 'yoga', labelEn: 'Yoga', labelRu: 'Йога' },
        { value: 'pilates', labelEn: 'Pilates', labelRu: 'Пилатес' },
        { value: 'crossfit', labelEn: 'CrossFit', labelRu: 'Кроссфит' },
        { value: 'swimming', labelEn: 'Swimming', labelRu: 'Плавание' },
        { value: 'martial_arts', labelEn: 'Martial Arts', labelRu: 'Единоборства' },
      ]},
      { key: 'dates', type: 'daterange', labelEn: 'Dates', labelRu: 'Даты', required: true },
      { key: 'notes', type: 'textarea', labelEn: 'Additional wishes', labelRu: 'Дополнительные пожелания', required: false },
    ],
    sort_order: 9,
  },
  {
    vertical_id: 'other',
    icon: '💬',
    name_en: 'Other',
    name_ru: 'Другое',
    short_desc_en: 'Custom request',
    short_desc_ru: 'Другой запрос',
    cta_text_en: 'Send Request',
    cta_text_ru: 'Отправить запрос',
    popularity_score: 10,
    request_types: [
      { value: 'general_inquiry', labelEn: 'General Inquiry', labelRu: 'Общий запрос' },
      { value: 'partnership', labelEn: 'Partnership', labelRu: 'Партнёрство' },
      { value: 'feedback', labelEn: 'Feedback', labelRu: 'Обратная связь' },
    ],
    fields: [
      { key: 'notes', type: 'textarea', labelEn: 'Your request', labelRu: 'Ваш запрос', placeholderEn: 'Tell us what you need...', placeholderRu: 'Расскажите, что вам нужно...', required: true },
    ],
    sort_order: 100,
  },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Insert intake configs
    const { data: intakeData, error: intakeError } = await supabase
      .from("sys_intake_configs")
      .upsert(INTAKE_VERTICALS, { onConflict: "vertical_id" })
      .select();

    if (intakeError) {
      console.error("Intake config error:", intakeError);
      throw new Error(`Intake configs: ${intakeError.message}`);
    }

    // Insert lead configs  
    const { data: leadData, error: leadError } = await supabase
      .from("sys_lead_configs")
      .upsert(LEAD_VERTICALS, { onConflict: "vertical_id" })
      .select();

    if (leadError) {
      console.error("Lead config error:", leadError);
      throw new Error(`Lead configs: ${leadError.message}`);
    }

    return new Response(
      JSON.stringify({
        success: true,
        intake_count: intakeData?.length || 0,
        lead_count: leadData?.length || 0,
        message: "Seed data inserted successfully",
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error("Seed error:", errorMessage);
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
