/**
 * PropertyPdfBrochure — Generate a beautiful PDF with property details
 */
import React, { useState } from 'react';
import { logger } from '@/lib/logger';
import { Download, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { toast } from 'sonner';
import { getPropertyTypeLabel, getDistrictLabel } from '@/lib/taxonomies';

interface PropertyForPdf {
  title_en: string;
  title_ru?: string;
  description_en?: string;
  description_ru?: string;
  property_type?: string;
  district?: string;
  bedrooms?: number;
  bathrooms?: number;
  area_sqm?: number;
  max_guests?: number;
  price?: number;
  price_per_night?: number;
  price_period?: string;
  cover_image?: string;
  images?: string[];
  rating?: number;
  amenities?: string[];
}

export function PropertyPdfButton({ property, variant = 'ghost', size = 'sm', className }: {
  property: PropertyForPdf;
  variant?: 'ghost' | 'outline' | 'default';
  size?: 'sm' | 'default';
  className?: string;
}) {
  const { language } = useLanguage();
  const isRu = language === 'ru';
  const [generating, setGenerating] = useState(false);

  const handleGenerate = async (e: React.MouseEvent) => {
    e.stopPropagation();
    setGenerating(true);

    try {
      const [{ default: jsPDF }, { loadCyrillicFont }] = await Promise.all([
        import('jspdf'),
        import('@/utils/pdfFonts'),
      ]);
      const doc = new jsPDF('p', 'mm', 'a4');
      await loadCyrillicFont(doc);
      const pageW = 210;
      const margin = 15;
      const contentW = pageW - margin * 2;
      let y = margin;

      // Background
      doc.setFillColor(250, 250, 250);
      doc.rect(0, 0, 210, 297, 'F');

      // Header
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text('myUNO · Property Brochure', margin, y);
      y += 8;

      // Cover image
      if (property.cover_image) {
        try {
          const img = await loadImage(property.cover_image);
          const imgH = (contentW / img.width) * img.height;
          const maxH = 80;
          const finalH = Math.min(imgH, maxH);
          doc.addImage(img, 'JPEG', margin, y, contentW, finalH);
          y += finalH + 6;
        } catch {
          // Skip image on error
        }
      }

      // Title
      doc.setFontSize(20);
      doc.setTextColor(30);
      const title = isRu ? (property.title_ru || property.title_en) : property.title_en;
      const titleLines = doc.splitTextToSize(title, contentW);
      doc.text(titleLines, margin, y);
      y += titleLines.length * 8 + 4;

      // Location
      if (property.district) {
        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text(getDistrictLabel(property.district, isRu ? 'ru' : 'en') + ', Phuket', margin, y);
        y += 7;
      }

      // Specs bar
      y += 3;
      doc.setDrawColor(220);
      doc.line(margin, y, margin + contentW, y);
      y += 6;

      doc.setFontSize(10);
      doc.setTextColor(60);
      const specs = [
        property.property_type ? getPropertyTypeLabel(property.property_type, isRu ? 'ru' : 'en') : null,
        property.bedrooms != null ? `${property.bedrooms} ${isRu ? 'спал.' : 'bed'}` : null,
        property.bathrooms != null ? `${property.bathrooms} ${isRu ? 'ванн.' : 'bath'}` : null,
        property.area_sqm ? `${property.area_sqm} м²` : null,
        property.max_guests ? `${property.max_guests} ${isRu ? 'гост.' : 'guests'}` : null,
      ].filter(Boolean);
      doc.text(specs.join('  ·  '), margin, y);
      y += 6;

      // Price
      const price = property.price_per_night || property.price;
      if (price) {
        doc.setFontSize(14);
        doc.setTextColor(30);
        const period = property.price_period || 'night';
        const periodLabel = isRu
          ? ({ night: '/ночь', month: '/мес', week: '/нед', year: '/год', total: '' }[period] || '')
          : ({ night: '/night', month: '/mo', week: '/week', year: '/year', total: '' }[period] || '');
        doc.text(`฿${price.toLocaleString()}${periodLabel}`, margin, y);
        y += 8;
      }

      if (property.rating) {
        doc.setFontSize(10);
        doc.setTextColor(80);
        doc.text(`★ ${property.rating.toFixed(1)}`, margin, y);
        y += 7;
      }

      doc.setDrawColor(220);
      doc.line(margin, y, margin + contentW, y);
      y += 8;

      // Description
      const desc = isRu ? (property.description_ru || property.description_en) : (property.description_en || property.description_ru);
      if (desc) {
        doc.setFontSize(10);
        doc.setTextColor(60);
        const descLines = doc.splitTextToSize(desc.slice(0, 800), contentW);
        doc.text(descLines, margin, y);
        y += descLines.length * 5 + 6;
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(180);
      doc.text('Generated by myUNO · myuno.app', margin, 290);

      // Download
      const filename = `${(title || 'property').replace(/[^a-zA-Zа-яА-Я0-9]/g, '_').slice(0, 40)}.pdf`;
      doc.save(filename);
      toast.success(isRu ? 'PDF скачан!' : 'PDF downloaded!');
    } catch (err) {
      logger.error('PDF generation error:', err);
      toast.error(isRu ? 'Ошибка генерации PDF' : 'Failed to generate PDF');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Button
      variant={variant}
      size={size}
      className={className}
      onClick={handleGenerate}
      disabled={generating}
    >
      {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
      <span className="hidden sm:inline ml-1.5">
        {generating ? (isRu ? 'Создание...' : 'Generating...') : 'PDF'}
      </span>
    </Button>
  );
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}
