// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search myUNO property listings on Phuket. Filter by city, min/max price (USD/THB stored as numeric) and bedrooms. Returns up to `limit` rows.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Free-text query matched against title/description."),
    city: z.string().trim().max(80).optional().describe("City filter, e.g. 'Phuket'."),
    minPrice: z.number().nonnegative().optional(),
    maxPrice: z.number().nonnegative().optional(),
    bedrooms: z.number().int().nonnegative().max(20).optional(),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, minPrice, maxPrice, bedrooms, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("properties").select("*").limit(limit);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (typeof minPrice === "number") q = q.gte("price", minPrice);
    if (typeof maxPrice === "number") q = q.lte("price", maxPrice);
    if (typeof bedrooms === "number") q = q.eq("bedrooms", bedrooms);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List services from the myUNO catalog. Optionally filter by category slug and free-text query.",
  inputSchema: {
    query: z2.string().trim().max(200).optional(),
    category: z2.string().trim().max(80).optional().describe("Category slug, e.g. 'legal'."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("services").select("*").limit(limit);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category_slug", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in myUNO user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kakkwibljrjsawxgnupk";
var mcp_default = defineMcp({
  name: "myuno-mcp",
  title: "myUNO",
  version: "0.1.0",
  instructions: "Tools for myUNO \u2014 a Phuket SuperApp for foreigners. Use `search_properties` to browse property listings, `list_services` to browse the service catalog, and `whoami` to identify the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_properties_default, list_services_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
