
-- Replace stale owner_properties table with a view pointing to properties
-- All 15 records are duplicates with diverging timestamps, causing stale data bugs

-- Step 1: Drop the stale table (no FKs reference it directly)
DROP TABLE IF EXISTS public.owner_properties CASCADE;

-- Step 2: Create view that maps properties columns to owner_properties column names
CREATE OR REPLACE VIEW public.owner_properties AS
SELECT
  id,
  owner_id,
  title,
  title_ru,
  address,
  district,
  property_type,
  bedrooms,
  bathrooms,
  area_sqm,
  description_en AS description,
  description_ru,
  cover_image,
  images,
  management_type,
  is_rented,
  rental_platform,
  status,
  verified_at,
  verified_by,
  notes,
  created_at,
  updated_at,
  marketplace_property_id,
  price_per_night,
  min_stay_nights,
  max_guests,
  deposit_amount,
  deposit_currency,
  check_in_time,
  check_out_time,
  house_rules,
  house_rules_ru,
  cancellation_policy,
  instant_booking,
  seasonal_pricing,
  weekly_discount,
  monthly_discount,
  deposit_type,
  electricity_included,
  electricity_unit_price,
  electricity_provider,
  electricity_metering,
  electricity_notes,
  electricity_notes_ru,
  water_included,
  water_unit_price,
  water_notes,
  water_notes_ru,
  included_services,
  extra_services,
  cleaning_included,
  cleaning_frequency,
  extra_cleaning_price,
  linen_change_price,
  linen_change_frequency,
  early_checkin_price,
  late_checkout_price,
  key_handover,
  check_in_instructions_ru,
  transfer_available,
  transfer_airport_price,
  transfer_notes,
  transfer_notes_ru,
  extra_guest_price,
  extra_guest_threshold,
  internet_speed,
  internet_provider,
  manager_name,
  manager_phone,
  manager_line_id,
  parking_included,
  parking_spaces,
  parking_notes,
  pets_allowed,
  pet_deposit,
  pet_notes,
  pet_notes_ru,
  quiet_hours_start,
  quiet_hours_end,
  parties_allowed,
  max_party_guests,
  children_friendly,
  has_crib,
  has_high_chair,
  late_checkout_penalty,
  smoking_penalty,
  emergency_contact_name,
  emergency_contact_phone,
  host_languages,
  check_in_instructions,
  project_id,
  floor,
  unit_number,
  view_type,
  furnishing_level,
  equipment,
  ical_token,
  lat,
  lng,
  rooms,
  management_company_id,
  accessibility_features
FROM properties;

-- Step 3: Set security invoker
ALTER VIEW public.owner_properties SET (security_invoker = true);
