
-- =====================================================
-- FULL SEED DATA FOR ALL MARKETPLACE CATEGORIES
-- =====================================================

-- Baby & Kids (0 -> 15 products)
INSERT INTO marketplace_products (category_slug, subcategory, name_en, name_ru, description_en, description_ru, price, original_price, currency, unit, unit_ru, cover_image, in_stock, is_popular, is_new, is_active, vendor_name, vendor_name_ru, sort_order, is_shippable_international, weight_kg) VALUES
('baby-kids', 'diapers', 'Pampers Premium Care Diapers Size 4', 'Подгузники Pampers Premium Care Размер 4', 'Ultra-soft diapers with up to 12 hours of protection. Dermatologically tested, hypoallergenic.', 'Ультрамягкие подгузники с защитой до 12 часов. Дерматологически протестированы, гипоаллергенны.', 890, 1050, 'THB', 'pack/52pcs', 'упак/52шт', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400', true, true, false, true, 'Pampers Thailand', 'Pampers Таиланд', 1, false, 1.2),
('baby-kids', 'diapers', 'Huggies Ultra Soft Diapers Size 3', 'Подгузники Huggies Ultra Soft Размер 3', 'Breathable diapers with wetness indicator. Gentle on baby skin.', 'Дышащие подгузники с индикатором влажности. Нежные к коже малыша.', 750, null, 'THB', 'pack/44pcs', 'упак/44шт', 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400', true, false, false, true, 'Huggies', 'Huggies', 2, false, 1.0),
('baby-kids', 'food', 'Gerber Organic Baby Cereal Rice', 'Детская каша Gerber Органик Рисовая', 'USDA Organic certified rice cereal for babies 4+ months. No artificial flavors.', 'Рисовая каша с сертификатом USDA Organic для детей от 4 месяцев. Без искусственных добавок.', 320, null, 'THB', '227g', '227г', 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=400', true, true, false, true, 'Gerber', 'Gerber', 3, true, 0.3),
('baby-kids', 'food', 'Hipp Organic Baby Formula Stage 2', 'Смесь Hipp Organic Этап 2', 'Organic follow-on formula for babies 6-12 months. With DHA and prebiotics.', 'Органическая смесь для детей 6-12 месяцев. С DHA и пребиотиками.', 1450, 1600, 'THB', '800g', '800г', 'https://images.unsplash.com/photo-1584839404042-8bc22a0a6b6f?w=400', true, true, false, true, 'Hipp', 'Hipp', 4, true, 0.9),
('baby-kids', 'toys', 'Fisher-Price Laugh & Learn Smart Phone', 'Телефон Fisher-Price Смейся и Учись', 'Interactive toy phone with songs, phrases and light-up buttons. Ages 6-36 months.', 'Интерактивный телефон с песнями, фразами и светящимися кнопками. Возраст 6-36 месяцев.', 650, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400', true, true, true, true, 'Fisher-Price', 'Fisher-Price', 5, true, 0.3),
('baby-kids', 'toys', 'Lego Duplo My First Animal Brick Box', 'Lego Duplo Мои первые животные', 'Colorful animal building blocks for toddlers 18+ months. 34 pieces.', 'Цветные кубики с животными для малышей от 18 месяцев. 34 детали.', 1290, null, 'THB', 'set', 'набор', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400', true, true, false, true, 'LEGO', 'LEGO', 6, true, 0.5),
('baby-kids', 'care', 'Mustela Gentle Cleansing Gel', 'Mustela Мягкий очищающий гель', 'Plant-based cleansing gel for hair and body. Safe from birth. 500ml.', 'Очищающий гель на растительной основе для волос и тела. Безопасен с рождения. 500мл.', 890, null, 'THB', '500ml', '500мл', 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=400', true, false, false, true, 'Mustela', 'Mustela', 7, true, 0.6),
('baby-kids', 'care', 'Aveeno Baby Daily Moisture Lotion', 'Aveeno Baby Ежедневный увлажняющий лосьон', 'Colloidal oatmeal formula for 24-hour moisture. Fragrance-free.', 'Формула с коллоидной овсянкой для 24-часового увлажнения. Без отдушек.', 520, null, 'THB', '227ml', '227мл', 'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400', true, false, false, true, 'Aveeno', 'Aveeno', 8, true, 0.3),
('baby-kids', 'clothing', 'Carters Organic Cotton Bodysuit 3-Pack', 'Carters Боди из органического хлопка 3шт', 'Soft organic cotton bodysuits in neutral colors. Snap buttons for easy changes.', 'Мягкие боди из органического хлопка в нейтральных цветах. Кнопки для удобной смены.', 890, 1100, 'THB', '3pcs', '3шт', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400', true, true, true, true, 'Carters', 'Carters', 9, true, 0.2),
('baby-kids', 'clothing', 'H&M Baby Sleeping Bag', 'H&M Детский спальный мешок', 'Cozy sleeping bag with zipper. 100% cotton lining. TOG 2.5.', 'Уютный спальный мешок на молнии. Подкладка 100% хлопок. TOG 2.5.', 750, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400', true, false, false, true, 'H&M', 'H&M', 10, true, 0.4),
('baby-kids', 'gear', 'Baby Bjorn Bouncer Bliss', 'Baby Bjorn Шезлонг Bliss', 'Ergonomic baby bouncer with natural rocking. Machine washable fabric.', 'Эргономичный шезлонг с естественным покачиванием. Ткань можно стирать в машине.', 6500, 7200, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=400', true, true, false, true, 'BabyBjorn', 'BabyBjorn', 11, true, 2.5),
('baby-kids', 'gear', 'Philips Avent Natural Bottles Set', 'Philips Avent Набор бутылочек Natural', 'Anti-colic bottles with soft nipple. BPA-free. 4oz/9oz combo pack.', 'Антиколиковые бутылочки с мягкой соской. Без BPA. Комбо-набор 125мл/260мл.', 1350, null, 'THB', 'set/4pcs', 'набор/4шт', 'https://images.unsplash.com/photo-1540479859555-17af45c78602?w=400', true, true, false, true, 'Philips Avent', 'Philips Avent', 12, true, 0.5),
('baby-kids', 'safety', 'Summer Infant Baby Monitor 2.0', 'Summer Infant Видеоняня 2.0', 'Digital video monitor with 2.4 inch color LCD screen. Night vision, two-way talk.', 'Цифровая видеоняня с 2.4 дюймовым цветным LCD экраном. Ночное видение, двусторонняя связь.', 3200, 3800, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1584839404042-8bc22a0a6b6f?w=400', true, true, true, true, 'Summer Infant', 'Summer Infant', 13, true, 0.4),
('baby-kids', 'safety', 'Safety 1st Cabinet Locks 12-Pack', 'Safety 1st Замки для шкафов 12шт', 'Child-proof magnetic cabinet locks. Easy installation, no tools needed.', 'Детские магнитные замки для шкафов. Простая установка без инструментов.', 650, null, 'THB', '12pcs', '12шт', 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400', true, false, false, true, 'Safety 1st', 'Safety 1st', 14, true, 0.3),
('baby-kids', 'toys', 'Sophie la Girafe Teether', 'Жираф Софи Прорезыватель', 'Iconic natural rubber teething toy from France. 100% natural rubber.', 'Культовый прорезыватель из Франции. 100% натуральный каучук.', 890, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400', true, true, false, true, 'Sophie la Girafe', 'Sophie la Girafe', 15, true, 0.1);

-- Health & Pharmacy (0 -> 18 products)
INSERT INTO marketplace_products (category_slug, subcategory, name_en, name_ru, description_en, description_ru, price, original_price, currency, unit, unit_ru, cover_image, in_stock, is_popular, is_new, is_active, vendor_name, vendor_name_ru, sort_order, is_shippable_international, weight_kg) VALUES
('health-pharmacy', 'vitamins', 'Blackmores Vitamin C 1000mg', 'Blackmores Витамин C 1000мг', 'High-potency vitamin C for immune support. 60 tablets.', 'Высокодозный витамин С для поддержки иммунитета. 60 таблеток.', 650, null, 'THB', '60 tablets', '60 таблеток', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', true, true, false, true, 'Blackmores', 'Blackmores', 1, true, 0.15),
('health-pharmacy', 'vitamins', 'Centrum Silver Adults 50+', 'Centrum Silver Взрослые 50+', 'Complete multivitamin for adults 50 and older. 100 tablets.', 'Полный комплекс витаминов для взрослых от 50 лет. 100 таблеток.', 890, 1050, 'THB', '100 tablets', '100 таблеток', 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400', true, true, false, true, 'Centrum', 'Centrum', 2, true, 0.2),
('health-pharmacy', 'vitamins', 'Natures Bounty Fish Oil Omega-3', 'Natures Bounty Рыбий жир Омега-3', 'Triple strength fish oil 1400mg. Supports heart health. 130 softgels.', 'Тройная сила рыбьего жира 1400мг. Поддержка сердца. 130 капсул.', 1250, null, 'THB', '130 softgels', '130 капсул', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', true, true, false, true, 'Natures Bounty', 'Natures Bounty', 3, true, 0.25),
('health-pharmacy', 'pain-relief', 'Tylenol Extra Strength 500mg', 'Tylenol Extra Strength 500мг', 'Fast-acting pain relief and fever reducer. 100 caplets.', 'Быстродействующее обезболивающее и жаропонижающее. 100 капсул.', 420, null, 'THB', '100 caplets', '100 капсул', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', true, true, false, true, 'Tylenol', 'Tylenol', 4, false, 0.12),
('health-pharmacy', 'pain-relief', 'Salonpas Pain Relief Patches', 'Salonpas Обезболивающие пластыри', 'Effective muscle and joint pain relief. Box of 40 patches.', 'Эффективное обезболивание мышц и суставов. Упаковка 40 пластырей.', 380, null, 'THB', '40 patches', '40 пластырей', 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400', true, true, true, true, 'Salonpas', 'Salonpas', 5, true, 0.1),
('health-pharmacy', 'digestive', 'Probiotics Lactobacillus Complex', 'Пробиотики Лактобактерии Комплекс', '10 billion CFU probiotic blend. Supports digestive health. 30 capsules.', '10 миллиардов КОЕ пробиотиков. Поддержка пищеварения. 30 капсул.', 750, null, 'THB', '30 capsules', '30 капсул', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', true, false, false, true, 'Pharmacy Brand', 'Аптечный бренд', 6, true, 0.08),
('health-pharmacy', 'digestive', 'Gaviscon Double Action Liquid', 'Gaviscon Двойное действие жидкость', 'Fast relief from heartburn and acid reflux. 300ml bottle.', 'Быстрое облегчение изжоги и кислотного рефлюкса. Флакон 300мл.', 450, null, 'THB', '300ml', '300мл', 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400', true, true, false, true, 'Gaviscon', 'Gaviscon', 7, false, 0.35),
('health-pharmacy', 'first-aid', 'Johnson First Aid Kit Complete', 'Johnson Аптечка первой помощи полная', 'Complete first aid kit with 140 items. Perfect for home and travel.', 'Полная аптечка с 140 предметами. Идеально для дома и путешествий.', 890, 1100, 'THB', 'kit', 'набор', 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400', true, true, false, true, 'Johnson', 'Johnson', 8, true, 0.5),
('health-pharmacy', 'first-aid', 'Band-Aid Flexible Fabric 100 Count', 'Band-Aid Гибкий пластырь 100шт', 'Breathable fabric bandages for all wound types. Variety pack.', 'Дышащие тканевые пластыри для всех типов ран. Набор разных размеров.', 320, null, 'THB', '100pcs', '100шт', 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400', true, false, false, true, 'Band-Aid', 'Band-Aid', 9, true, 0.08),
('health-pharmacy', 'cold-flu', 'Strepsils Honey Lemon Lozenges', 'Strepsils Мёд и Лимон Леденцы', 'Sore throat relief with antibacterial action. 24 lozenges.', 'Облегчение боли в горле с антибактериальным действием. 24 леденца.', 180, null, 'THB', '24 lozenges', '24 леденца', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', true, true, false, true, 'Strepsils', 'Strepsils', 10, true, 0.05),
('health-pharmacy', 'cold-flu', 'Vicks VapoRub Ointment', 'Vicks VapoRub Мазь', 'Topical cough suppressant. Relieves cough and congestion. 50g.', 'Местное средство от кашля. Облегчает кашель и заложенность. 50г.', 220, null, 'THB', '50g', '50г', 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400', true, true, false, true, 'Vicks', 'Vicks', 11, true, 0.08),
('health-pharmacy', 'allergy', 'Zyrtec Cetirizine 10mg', 'Zyrtec Цетиризин 10мг', '24-hour allergy relief. Non-drowsy formula. 30 tablets.', '24-часовое облегчение аллергии. Не вызывает сонливости. 30 таблеток.', 380, null, 'THB', '30 tablets', '30 таблеток', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400', true, true, false, true, 'Zyrtec', 'Zyrtec', 12, false, 0.05),
('health-pharmacy', 'eye-care', 'Systane Ultra Lubricant Eye Drops', 'Systane Ultra Увлажняющие капли', 'Long-lasting dry eye relief. Preservative-free. 10ml.', 'Длительное облегчение сухости глаз. Без консервантов. 10мл.', 450, null, 'THB', '10ml', '10мл', 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400', true, false, false, true, 'Systane', 'Systane', 13, true, 0.05),
('health-pharmacy', 'dental', 'Sensodyne Repair Protect Toothpaste', 'Sensodyne Восстановление и Защита', 'Clinically proven relief for sensitive teeth. 100g tube.', 'Клинически доказанное облегчение чувствительности зубов. Тюбик 100г.', 280, null, 'THB', '100g', '100г', 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400', true, true, false, true, 'Sensodyne', 'Sensodyne', 14, true, 0.12),
('health-pharmacy', 'dental', 'Listerine Cool Mint Mouthwash', 'Listerine Прохладная Мята', 'Kills 99.9% of germs. Fresh breath for 24 hours. 500ml.', 'Убивает 99.9% бактерий. Свежее дыхание на 24 часа. 500мл.', 220, null, 'THB', '500ml', '500мл', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', true, false, false, true, 'Listerine', 'Listerine', 15, false, 0.55),
('health-pharmacy', 'skin-care', 'Bepanthen Wound Healing Cream', 'Bepanthen Заживляющий крем', 'Promotes natural healing of minor wounds. 30g tube.', 'Способствует естественному заживлению мелких ран. Тюбик 30г.', 320, null, 'THB', '30g', '30г', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400', true, true, false, true, 'Bepanthen', 'Bepanthen', 16, true, 0.05),
('health-pharmacy', 'skin-care', 'Eucerin Original Healing Cream', 'Eucerin Оригинальный заживляющий крем', 'Intense moisturizer for very dry skin. Fragrance-free. 454g.', 'Интенсивное увлажнение для очень сухой кожи. Без отдушек. 454г.', 890, null, 'THB', '454g', '454г', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400', true, false, false, true, 'Eucerin', 'Eucerin', 17, true, 0.5),
('health-pharmacy', 'supplements', 'Melatonin 5mg Sleep Support', 'Мелатонин 5мг Поддержка сна', 'Natural sleep aid. Fast dissolve tablets. 60 tablets.', 'Натуральное средство для сна. Быстрорастворимые таблетки. 60 таблеток.', 480, null, 'THB', '60 tablets', '60 таблеток', 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?w=400', true, true, true, true, 'Pharmacy Brand', 'Аптечный бренд', 18, true, 0.08);

-- Additional Home & Living products (4 -> 16 products)
INSERT INTO marketplace_products (category_slug, subcategory, name_en, name_ru, description_en, description_ru, price, original_price, currency, unit, unit_ru, cover_image, in_stock, is_popular, is_new, is_active, vendor_name, vendor_name_ru, sort_order, is_shippable_international, weight_kg) VALUES
('home-decor', 'bedding', 'Egyptian Cotton Sheet Set 400TC', 'Комплект простыней из египетского хлопка 400TC', 'Luxurious 400 thread count sheets. Silky smooth finish. King size.', 'Роскошные простыни плотностью 400 нитей. Шелковистая гладкость. Размер King.', 3500, 4200, 'THB', 'set', 'комплект', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400', true, true, false, true, 'Premium Home', 'Premium Home', 5, true, 1.5),
('home-decor', 'bedding', 'Memory Foam Pillow Contour', 'Ортопедическая подушка Memory Foam', 'Ergonomic contour pillow for neck support. Cooling gel layer.', 'Эргономичная контурная подушка для поддержки шеи. Охлаждающий гелевый слой.', 1450, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400', true, true, true, true, 'Sleep Well', 'Sleep Well', 6, true, 1.2),
('home-decor', 'kitchen', 'Le Creuset Cast Iron Dutch Oven', 'Le Creuset Чугунный горшок', 'Premium enameled cast iron. 5.5 qt capacity. Flame color.', 'Премиальный эмалированный чугун. Объём 5.2л. Цвет пламя.', 12500, 14000, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', true, true, false, true, 'Le Creuset', 'Le Creuset', 7, true, 5.5),
('home-decor', 'kitchen', 'Japanese Knife Set 5-Piece', 'Японские ножи набор 5шт', 'Damascus steel blades. Ergonomic handles. Chef, Santoku, Utility, Paring, Bread.', 'Лезвия из дамасской стали. Эргономичные ручки. Шеф, Сантоку, Универсальный, Для овощей, Хлебный.', 8900, 10500, 'THB', 'set', 'набор', 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400', true, true, false, true, 'Tojiro', 'Tojiro', 8, true, 1.8),
('home-decor', 'kitchen', 'Nespresso Vertuo Coffee Machine', 'Кофемашина Nespresso Vertuo', 'Centrifusion technology for perfect crema. 5 cup sizes. With 12 capsules.', 'Технология Centrifusion для идеальной крема. 5 размеров чашек. С 12 капсулами.', 7500, 8500, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400', true, true, true, true, 'Nespresso', 'Nespresso', 9, true, 4.0),
('home-decor', 'bathroom', 'Dyson Supersonic Hair Dryer', 'Фен Dyson Supersonic', 'Intelligent heat control. Powerful digital motor. 4 magnetic attachments.', 'Интеллектуальный контроль температуры. Мощный цифровой мотор. 4 магнитные насадки.', 16500, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=400', true, true, false, true, 'Dyson', 'Dyson', 10, true, 0.7),
('home-decor', 'bathroom', 'Luxury Turkish Cotton Towel Set', 'Набор турецких полотенец Люкс', 'Premium 700 GSM cotton. Set of 6: 2 bath, 2 hand, 2 face.', 'Премиальный хлопок 700 GSM. Набор 6шт: 2 банных, 2 для рук, 2 для лица.', 2800, 3400, 'THB', 'set/6pcs', 'набор/6шт', 'https://images.unsplash.com/photo-1600369671854-8b61a0c96d48?w=400', true, true, false, true, 'Turkish Home', 'Turkish Home', 11, true, 2.0),
('home-decor', 'storage', 'Minimalist Wooden Shelf Unit', 'Минималистичная деревянная полка', 'Solid oak construction. 5 tiers. Scandinavian design.', 'Конструкция из массива дуба. 5 уровней. Скандинавский дизайн.', 4500, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=400', true, false, true, true, 'Nordic Design', 'Nordic Design', 12, false, 12.0),
('home-decor', 'lighting', 'Philips Hue Starter Kit', 'Philips Hue Стартовый набор', 'Smart LED bulbs with bridge. 4 bulbs, 16 million colors. Voice control ready.', 'Умные LED лампы с мостом. 4 лампы, 16 миллионов цветов. Готово к голосовому управлению.', 5500, 6200, 'THB', 'set', 'набор', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', true, true, true, true, 'Philips', 'Philips', 13, true, 1.0),
('home-decor', 'lighting', 'Industrial Pendant Lamp', 'Промышленный подвесной светильник', 'Vintage Edison style. Adjustable height. Matte black finish.', 'Стиль винтаж Эдисон. Регулируемая высота. Матовый чёрный.', 1800, null, 'THB', 'pc', 'шт', 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=400', true, false, false, true, 'Loft Style', 'Loft Style', 14, true, 1.5),
('home-decor', 'decor', 'Handcrafted Ceramic Vase Set', 'Набор керамических ваз ручной работы', 'Set of 3 minimalist vases. Different sizes. Natural clay finish.', 'Набор из 3 минималистичных ваз. Разные размеры. Натуральная глина.', 2200, null, 'THB', 'set/3pcs', 'набор/3шт', 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=400', true, true, false, true, 'Artisan Studio', 'Artisan Studio', 15, true, 2.5),
('home-decor', 'decor', 'Botanical Print Frames Set', 'Набор ботанических принтов в рамах', 'Gallery wall set of 6 prints. Gold frames. Ready to hang.', 'Галерейный набор из 6 принтов. Золотые рамы. Готовы к подвешиванию.', 3200, 3800, 'THB', 'set/6pcs', 'набор/6шт', 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400', true, false, true, true, 'Art Frame', 'Art Frame', 16, true, 3.0);

-- Additional Drinks products (5 -> 15 products)
INSERT INTO marketplace_products (category_slug, subcategory, name_en, name_ru, description_en, description_ru, price, original_price, currency, unit, unit_ru, cover_image, in_stock, is_popular, is_new, is_active, vendor_name, vendor_name_ru, sort_order, is_shippable_international, weight_kg) VALUES
('drinks', 'water', 'Evian Natural Spring Water 1.5L', 'Evian Природная родниковая вода 1.5л', 'Premium mineral water from French Alps. Pack of 6 bottles.', 'Премиальная минеральная вода из французских Альп. Упаковка 6 бутылок.', 420, null, 'THB', '6x1.5L', '6x1.5л', 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400', true, true, false, true, 'Evian', 'Evian', 6, false, 9.0),
('drinks', 'water', 'San Pellegrino Sparkling Water', 'San Pellegrino Газированная вода', 'Italian sparkling mineral water. Perfect with meals. Pack of 6.', 'Итальянская газированная минеральная вода. Идеальна к еде. Упаковка 6.', 380, null, 'THB', '6x500ml', '6x500мл', 'https://images.unsplash.com/photo-1606168094336-48f205276929?w=400', true, true, false, true, 'San Pellegrino', 'San Pellegrino', 7, false, 3.5),
('drinks', 'juice', 'Fresh Orange Juice Premium', 'Свежевыжатый апельсиновый сок Премиум', '100% freshly squeezed oranges. No added sugar. Cold-pressed.', '100% свежевыжатые апельсины. Без добавления сахара. Холодного отжима.', 180, null, 'THB', '1L', '1л', 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400', true, true, false, true, 'Fresh Factory', 'Fresh Factory', 8, false, 1.1),
('drinks', 'juice', 'Pomegranate Juice Organic', 'Гранатовый сок Органик', 'Pure organic pomegranate juice. Rich in antioxidants.', 'Чистый органический гранатовый сок. Богат антиоксидантами.', 320, null, 'THB', '500ml', '500мл', 'https://images.unsplash.com/photo-1553177597-40eabbd1f5b8?w=400', true, false, true, true, 'Organic Farm', 'Органик Ферма', 9, false, 0.6),
('drinks', 'coffee', 'Lavazza Qualita Oro Ground Coffee', 'Lavazza Qualita Oro Молотый кофе', 'Premium Arabica blend. Medium roast. Floral and fruity notes.', 'Премиальная смесь Арабики. Средняя обжарка. Цветочные и фруктовые ноты.', 580, null, 'THB', '250g', '250г', 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=400', true, true, false, true, 'Lavazza', 'Lavazza', 10, true, 0.3),
('drinks', 'coffee', 'Nescafe Gold Blend Instant', 'Nescafe Gold Растворимый', 'Premium instant coffee with fine aroma. 200g jar.', 'Премиальный растворимый кофе с тонким ароматом. Банка 200г.', 450, null, 'THB', '200g', '200г', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400', true, true, false, true, 'Nescafe', 'Nescafe', 11, true, 0.25),
('drinks', 'tea', 'TWG Singapore Breakfast Tea', 'TWG Сингапурский завтрак', 'Luxury tea blend. Robust and full-bodied. 100g tin.', 'Люксовый чайный купаж. Крепкий и насыщенный. Банка 100г.', 890, null, 'THB', '100g', '100г', 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400', true, true, false, true, 'TWG Tea', 'TWG Tea', 12, true, 0.15),
('drinks', 'tea', 'Twinings Earl Grey Classic', 'Twinings Эрл Грей Классик', 'Classic bergamot-flavored black tea. Box of 100 tea bags.', 'Классический чёрный чай с бергамотом. Упаковка 100 пакетиков.', 350, null, 'THB', '100 bags', '100 пакетиков', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400', true, true, false, true, 'Twinings', 'Twinings', 13, true, 0.2),
('drinks', 'soda', 'Coca-Cola Original 24-Pack', 'Coca-Cola Оригинальная 24шт', 'Classic Coca-Cola in 330ml cans. Perfect for parties.', 'Классическая Coca-Cola в банках 330мл. Идеально для вечеринок.', 520, null, 'THB', '24x330ml', '24x330мл', 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400', true, true, false, true, 'Coca-Cola', 'Coca-Cola', 14, false, 8.5),
('drinks', 'energy', 'Red Bull Energy Drink 12-Pack', 'Red Bull Энергетик 12шт', 'Gives you wings. Original formula. 250ml cans.', 'Окрыляет. Оригинальная формула. Банки 250мл.', 680, null, 'THB', '12x250ml', '12x250мл', 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?w=400', true, true, false, true, 'Red Bull', 'Red Bull', 15, false, 3.5);

-- Add subcategories for categories that don't have them yet
INSERT INTO marketplace_subcategories (category_slug, slug, name_en, name_ru, icon, sort_order, is_active) 
SELECT * FROM (VALUES
  ('baby-kids', 'diapers', 'Diapers & Wipes', 'Подгузники и салфетки', '🧷', 1, true),
  ('baby-kids', 'food', 'Baby Food', 'Детское питание', '🍼', 2, true),
  ('baby-kids', 'toys', 'Toys', 'Игрушки', '🧸', 3, true),
  ('baby-kids', 'care', 'Baby Care', 'Уход за малышом', '🧴', 4, true),
  ('baby-kids', 'clothing', 'Clothing', 'Одежда', '👶', 5, true),
  ('baby-kids', 'gear', 'Gear & Equipment', 'Аксессуары', '🪑', 6, true),
  ('baby-kids', 'safety', 'Safety', 'Безопасность', '🔒', 7, true),
  ('health-pharmacy', 'vitamins', 'Vitamins & Supplements', 'Витамины и добавки', '💊', 1, true),
  ('health-pharmacy', 'pain-relief', 'Pain Relief', 'Обезболивающие', '🩹', 2, true),
  ('health-pharmacy', 'digestive', 'Digestive Health', 'Пищеварение', '🫄', 3, true),
  ('health-pharmacy', 'first-aid', 'First Aid', 'Первая помощь', '🏥', 4, true),
  ('health-pharmacy', 'cold-flu', 'Cold & Flu', 'Простуда и грипп', '🤧', 5, true),
  ('health-pharmacy', 'allergy', 'Allergy', 'Аллергия', '🌸', 6, true),
  ('health-pharmacy', 'eye-care', 'Eye Care', 'Уход за глазами', '👁️', 7, true),
  ('health-pharmacy', 'dental', 'Dental Care', 'Уход за зубами', '🦷', 8, true),
  ('health-pharmacy', 'skin-care', 'Skin Care', 'Уход за кожей', '🧴', 9, true),
  ('health-pharmacy', 'supplements', 'Sleep & Stress', 'Сон и стресс', '😴', 10, true),
  ('home-decor', 'bedding', 'Bedding', 'Постельное бельё', '🛏️', 1, true),
  ('home-decor', 'kitchen', 'Kitchen', 'Кухня', '🍳', 2, true),
  ('home-decor', 'bathroom', 'Bathroom', 'Ванная', '🚿', 3, true),
  ('home-decor', 'storage', 'Storage', 'Хранение', '📦', 4, true),
  ('home-decor', 'lighting', 'Lighting', 'Освещение', '💡', 5, true),
  ('home-decor', 'decor', 'Decor', 'Декор', '🖼️', 6, true),
  ('drinks', 'water', 'Water', 'Вода', '💧', 1, true),
  ('drinks', 'juice', 'Juice', 'Соки', '🍊', 2, true),
  ('drinks', 'coffee', 'Coffee', 'Кофе', '☕', 3, true),
  ('drinks', 'tea', 'Tea', 'Чай', '🍵', 4, true),
  ('drinks', 'soda', 'Soda', 'Газировка', '🥤', 5, true),
  ('drinks', 'energy', 'Energy Drinks', 'Энергетики', '⚡', 6, true)
) AS t(category_slug, slug, name_en, name_ru, icon, sort_order, is_active)
WHERE NOT EXISTS (
  SELECT 1 FROM marketplace_subcategories ms 
  WHERE ms.category_slug = t.category_slug AND ms.slug = t.slug
);
