-- ============================================================
-- STEP 2: Migrate data from owner_properties to properties
-- ============================================================

-- First, update existing properties that have matching owner_properties
UPDATE properties p
SET 
  owner_id = op.owner_id,
  title = op.title,
  management_type = op.management_type,
  is_rented = op.is_rented,
  rental_platform = op.rental_platform,
  status = op.status,
  verified_at = op.verified_at,
  verified_by = op.verified_by,
  notes = op.notes,
  price_per_night = op.price_per_night,
  deposit_amount = op.deposit_amount,
  deposit_currency = op.deposit_currency,
  deposit_type = op.deposit_type,
  weekly_discount = op.weekly_discount,
  monthly_discount = op.monthly_discount,
  seasonal_pricing = op.seasonal_pricing,
  check_in_time = op.check_in_time,
  check_out_time = op.check_out_time,
  house_rules = op.house_rules,
  house_rules_ru = op.house_rules_ru,
  cancellation_policy = op.cancellation_policy,
  electricity_included = op.electricity_included,
  electricity_unit_price = op.electricity_unit_price,
  electricity_provider = op.electricity_provider,
  electricity_metering = op.electricity_metering,
  electricity_notes = op.electricity_notes,
  electricity_notes_ru = op.electricity_notes_ru,
  water_included = op.water_included,
  water_unit_price = op.water_unit_price,
  water_notes = op.water_notes,
  water_notes_ru = op.water_notes_ru,
  included_services = op.included_services,
  extra_services = op.extra_services,
  cleaning_included = op.cleaning_included,
  cleaning_frequency = op.cleaning_frequency,
  extra_cleaning_price = op.extra_cleaning_price,
  linen_change_price = op.linen_change_price,
  linen_change_frequency = op.linen_change_frequency,
  ical_token = op.ical_token::text,
  purchase_price = op.purchase_price,
  purchase_date = op.purchase_date,
  rooms = op.rooms,
  parking_spaces = op.parking_spaces,
  parking_type = op.parking_type,
  pet_deposit = op.pet_deposit,
  total_floors = op.total_floors,
  legacy_owner_property_id = op.id
FROM owner_properties op
WHERE op.marketplace_property_id = p.id;

-- Insert owner_properties that don't have marketplace listing yet
INSERT INTO properties (
  id,
  owner_id,
  title,
  title_en,
  title_ru,
  description_en,
  description_ru,
  address,
  district,
  property_type,
  bedrooms,
  bathrooms,
  area_sqm,
  cover_image,
  images,
  max_guests,
  management_type,
  is_rented,
  rental_platform,
  status,
  verified_at,
  verified_by,
  notes,
  price_per_night,
  min_stay_nights,
  deposit_amount,
  deposit_currency,
  deposit_type,
  weekly_discount,
  monthly_discount,
  seasonal_pricing,
  check_in_time,
  check_out_time,
  house_rules,
  house_rules_ru,
  cancellation_policy,
  instant_booking,
  electricity_included,
  electricity_unit_price,
  electricity_provider,
  electricity_metering,
  electricity_notes,
  electricity_notes_ru,
  water_included,
  water_unit_price,
  water_notes,
  water_notes_ru,
  included_services,
  extra_services,
  cleaning_included,
  cleaning_frequency,
  extra_cleaning_price,
  linen_change_price,
  linen_change_frequency,
  ical_token,
  purchase_price,
  purchase_date,
  rooms,
  parking_spaces,
  parking_type,
  pet_deposit,
  total_floors,
  legacy_owner_property_id,
  listing_modes,
  is_active,
  listing_type,
  currency,
  lat,
  lng,
  floor,
  unit_number,
  view_type,
  furnishing_level,
  equipment,
  highlights
)
SELECT 
  gen_random_uuid(),
  op.owner_id,
  op.title,
  COALESCE(op.title, op.address),
  op.title_ru,
  op.description,
  op.description_ru,
  op.address,
  op.district,
  op.property_type,
  op.bedrooms,
  op.bathrooms,
  op.area_sqm,
  op.cover_image,
  op.images,
  op.max_guests,
  op.management_type,
  op.is_rented,
  op.rental_platform,
  op.status,
  op.verified_at,
  op.verified_by,
  op.notes,
  op.price_per_night,
  op.min_stay_nights,
  op.deposit_amount,
  op.deposit_currency,
  op.deposit_type,
  op.weekly_discount,
  op.monthly_discount,
  op.seasonal_pricing,
  op.check_in_time,
  op.check_out_time,
  op.house_rules,
  op.house_rules_ru,
  op.cancellation_policy,
  op.instant_booking,
  op.electricity_included,
  op.electricity_unit_price,
  op.electricity_provider,
  op.electricity_metering,
  op.electricity_notes,
  op.electricity_notes_ru,
  op.water_included,
  op.water_unit_price,
  op.water_notes,
  op.water_notes_ru,
  op.included_services,
  op.extra_services,
  op.cleaning_included,
  op.cleaning_frequency,
  op.extra_cleaning_price,
  op.linen_change_price,
  op.linen_change_frequency,
  op.ical_token::text,
  op.purchase_price,
  op.purchase_date,
  op.rooms,
  op.parking_spaces,
  op.parking_type,
  op.pet_deposit,
  op.total_floors,
  op.id,
  op.listing_modes,
  true,
  'rent',
  'THB',
  op.lat,
  op.lng,
  op.floor,
  op.unit_number,
  op.view_type,
  op.furnishing_level,
  op.equipment,
  op.highlights
FROM owner_properties op
WHERE op.marketplace_property_id IS NULL;