-- Wave 5 Phase 2: Drop 10 unused tables + 12 dead RPC functions
-- All verified: no code refs, no FK dependencies, no triggers, RPC callers only in autogenerated types

-- Drop dead RPC functions first (they reference the tables)
DROP FUNCTION IF EXISTS public.start_simulation_run CASCADE;
DROP FUNCTION IF EXISTS public.get_simulation_report CASCADE;
DROP FUNCTION IF EXISTS public.purge_simulation_run CASCADE;
DROP FUNCTION IF EXISTS public.link_simulation_entity CASCADE;
DROP FUNCTION IF EXISTS public.log_simulation_event CASCADE;
DROP FUNCTION IF EXISTS public.is_simulation_entity CASCADE;
DROP FUNCTION IF EXISTS public.resolve_verticals_for_task CASCADE;
DROP FUNCTION IF EXISTS public.resolve_life_tasks CASCADE;
DROP FUNCTION IF EXISTS public.resolve_verticals_for_situation CASCADE;
DROP FUNCTION IF EXISTS public.resolve_task_entities CASCADE;
DROP FUNCTION IF EXISTS public.resolve_tasks_for_vertical CASCADE;

-- Drop 10 unused tables
DROP TABLE IF EXISTS public.task_entity_map CASCADE;
DROP TABLE IF EXISTS public.vertical_life_tasks CASCADE;
DROP TABLE IF EXISTS public.data_provenance CASCADE;
DROP TABLE IF EXISTS public.simulation_events CASCADE;
DROP TABLE IF EXISTS public.simulation_entity_links CASCADE;
DROP TABLE IF EXISTS public.cancellation_policy_rules CASCADE;
DROP TABLE IF EXISTS public.owner_commission_tiers CASCADE;
DROP TABLE IF EXISTS public.platform_fees CASCADE;
DROP TABLE IF EXISTS public.booking_participants CASCADE;
DROP TABLE IF EXISTS public.store_products CASCADE;