 /**
  * Canonical Home Service Functions - Problem-Solution Catalog
  * These are the most common household problems and their solutions
  * Used for function-centric service ordering (vs provider-centric)
  */
 
 export interface ServiceFunction {
   id: string;
   category: ServiceCategory;
   nameEn: string;
   nameRu: string;
   descriptionEn: string;
   descriptionRu: string;
   icon: string;
   basePrice: number;
   currency: string;
   estimatedTime: string;
   estimatedTimeEn: string;
   estimatedTimeRu: string;
   includesEn: string[];
   includesRu: string[];
   isPopular?: boolean;
   isUrgent?: boolean;
   sortOrder: number;
 }
 
 export type ServiceCategory = 
   | 'ac'
   | 'plumbing'
   | 'electrical'
   | 'handyman'
   | 'appliance_repair'
   | 'cleaning'
   | 'pool'
   | 'garden'
   | 'pest_control'
   | 'security'
   | 'moving';
 
 export interface ServiceCategoryConfig {
   id: ServiceCategory;
   nameEn: string;
   nameRu: string;
   icon: string;
   color: string;
   sortOrder: number;
 }
 
 export const SERVICE_CATEGORIES: ServiceCategoryConfig[] = [
   { id: 'ac', nameEn: 'Air Conditioning', nameRu: 'Кондиционеры', icon: '❄️', color: 'blue', sortOrder: 1 },
   { id: 'plumbing', nameEn: 'Plumbing', nameRu: 'Сантехника', icon: '🔧', color: 'cyan', sortOrder: 2 },
   { id: 'electrical', nameEn: 'Electrical', nameRu: 'Электрика', icon: '⚡', color: 'yellow', sortOrder: 3 },
   { id: 'handyman', nameEn: 'Handyman', nameRu: 'Мастер на час', icon: '🛠️', color: 'orange', sortOrder: 4 },
   { id: 'appliance_repair', nameEn: 'Appliance Repair', nameRu: 'Ремонт техники', icon: '🔌', color: 'purple', sortOrder: 5 },
   { id: 'cleaning', nameEn: 'Cleaning', nameRu: 'Уборка', icon: '🧹', color: 'green', sortOrder: 6 },
   { id: 'pool', nameEn: 'Pool & Jacuzzi', nameRu: 'Бассейн и джакузи', icon: '🏊', color: 'sky', sortOrder: 7 },
   { id: 'garden', nameEn: 'Garden', nameRu: 'Сад и участок', icon: '🌿', color: 'emerald', sortOrder: 8 },
   { id: 'pest_control', nameEn: 'Pest Control', nameRu: 'Дезинсекция', icon: '🐜', color: 'red', sortOrder: 9 },
   { id: 'security', nameEn: 'Security', nameRu: 'Безопасность', icon: '🔒', color: 'slate', sortOrder: 10 },
   { id: 'moving', nameEn: 'Moving', nameRu: 'Переезд', icon: '📦', color: 'amber', sortOrder: 11 },
 ];
 
 export const HOME_SERVICE_FUNCTIONS: ServiceFunction[] = [
   // ❄️ AC - Air Conditioning
   {
     id: 'ac_cleaning',
     category: 'ac',
     nameEn: 'AC Cleaning',
     nameRu: 'Чистка кондиционера',
     descriptionEn: 'Professional deep cleaning of your air conditioner',
     descriptionRu: 'Профессиональная глубокая чистка кондиционера',
     icon: '🧼',
     basePrice: 800,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Filter washing', 'Coil cleaning', 'Disinfection', 'Pressure check'],
     includesRu: ['Промывка фильтров', 'Чистка радиатора', 'Дезинфекция', 'Проверка давления'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'ac_install',
     category: 'ac',
     nameEn: 'AC Installation',
     nameRu: 'Установка кондиционера',
     descriptionEn: 'Professional installation of a new air conditioner',
     descriptionRu: 'Профессиональная установка нового кондиционера',
     icon: '🏗️',
     basePrice: 3500,
     currency: 'THB',
     estimatedTime: '3-5h',
     estimatedTimeEn: '3-5 hours',
     estimatedTimeRu: '3-5 часов',
     includesEn: ['Indoor unit mounting', 'Outdoor unit mounting', 'Pipe installation', 'Commissioning'],
     includesRu: ['Монтаж внутреннего блока', 'Монтаж наружного блока', 'Прокладка трассы', 'Пуско-наладка'],
     sortOrder: 2,
   },
   {
     id: 'ac_repair',
     category: 'ac',
     nameEn: 'AC Repair',
     nameRu: 'Ремонт кондиционера',
     descriptionEn: 'Diagnostics and repair of air conditioner malfunctions',
     descriptionRu: 'Диагностика и устранение неисправностей кондиционера',
     icon: '🔧',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1-3h',
     estimatedTimeEn: '1-3 hours',
     estimatedTimeRu: '1-3 часа',
     includesEn: ['Diagnostics', 'Fault detection', 'Parts replacement', 'Testing'],
     includesRu: ['Диагностика', 'Поиск неисправности', 'Замена деталей', 'Проверка работы'],
     isUrgent: true,
     sortOrder: 3,
   },
   {
     id: 'ac_gas_refill',
     category: 'ac',
     nameEn: 'Freon Refill',
     nameRu: 'Заправка фреоном',
     descriptionEn: 'Refrigerant refill and leak check',
     descriptionRu: 'Заправка хладагента и проверка утечек',
     icon: '🧪',
     basePrice: 600,
     currency: 'THB',
     estimatedTime: '30m',
     estimatedTimeEn: '30 minutes',
     estimatedTimeRu: '30 минут',
     includesEn: ['Leak check', 'Gas refill', 'Pressure test'],
     includesRu: ['Проверка утечек', 'Заправка газа', 'Проверка давления'],
     sortOrder: 4,
   },
 
   // 🔧 Plumbing
   {
     id: 'leak_repair',
     category: 'plumbing',
     nameEn: 'Leak Repair',
     nameRu: 'Устранение течи',
     descriptionEn: 'Fix water leaks in pipes, faucets, or connections',
     descriptionRu: 'Устранение протечек в трубах, кранах или соединениях',
     icon: '💧',
     basePrice: 1200,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Leak detection', 'Seal replacement', 'Joint repair'],
     includesRu: ['Поиск течи', 'Замена прокладок', 'Ремонт соединений'],
     isPopular: true,
     isUrgent: true,
     sortOrder: 1,
   },
   {
     id: 'faucet_install',
     category: 'plumbing',
     nameEn: 'Faucet Installation',
     nameRu: 'Установка смесителя',
     descriptionEn: 'Install or replace kitchen or bathroom faucet',
     descriptionRu: 'Установка или замена смесителя на кухне или в ванной',
     icon: '🚰',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Old faucet removal', 'New faucet installation', 'Leak check'],
     includesRu: ['Демонтаж старого крана', 'Установка нового', 'Проверка на течь'],
     sortOrder: 2,
   },
   {
     id: 'drain_cleaning',
     category: 'plumbing',
     nameEn: 'Drain Cleaning',
     nameRu: 'Прочистка канализации',
     descriptionEn: 'Professional drain unclogging and cleaning',
     descriptionRu: 'Профессиональная прочистка засоров в канализации',
     icon: '🕳️',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Blockage removal', 'Pipe cleaning', 'Preventive treatment'],
     includesRu: ['Устранение засора', 'Прочистка труб', 'Профилактика'],
     isPopular: true,
     sortOrder: 3,
   },
   {
     id: 'toilet_repair',
     category: 'plumbing',
     nameEn: 'Toilet Repair',
     nameRu: 'Ремонт унитаза',
     descriptionEn: 'Fix toilet flushing mechanism and leaks',
     descriptionRu: 'Ремонт сливного механизма и устранение течей',
     icon: '🚽',
     basePrice: 1000,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Mechanism check', 'Parts replacement', 'Leak repair'],
     includesRu: ['Проверка механизма', 'Замена деталей', 'Устранение течи'],
     sortOrder: 4,
   },
   {
     id: 'toilet_install',
     category: 'plumbing',
     nameEn: 'Toilet Installation',
     nameRu: 'Установка унитаза',
     descriptionEn: 'Professional toilet installation or replacement',
     descriptionRu: 'Профессиональная установка или замена унитаза',
     icon: '🚽',
     basePrice: 2500,
     currency: 'THB',
     estimatedTime: '2h',
     estimatedTimeEn: '2 hours',
     estimatedTimeRu: '2 часа',
     includesEn: ['Old toilet removal', 'New toilet installation', 'Sealing', 'Testing'],
     includesRu: ['Демонтаж старого', 'Установка нового', 'Герметизация', 'Проверка'],
     sortOrder: 5,
   },
   {
     id: 'water_heater',
     category: 'plumbing',
     nameEn: 'Water Heater Service',
     nameRu: 'Водонагреватель',
     descriptionEn: 'Water heater installation, repair, or maintenance',
     descriptionRu: 'Установка, ремонт или обслуживание водонагревателя',
     icon: '🔥',
     basePrice: 2500,
     currency: 'THB',
     estimatedTime: '2-3h',
     estimatedTimeEn: '2-3 hours',
     estimatedTimeRu: '2-3 часа',
     includesEn: ['Inspection', 'Installation/Repair', 'Safety check'],
     includesRu: ['Осмотр', 'Установка/Ремонт', 'Проверка безопасности'],
     sortOrder: 6,
   },
 
   // ⚡ Electrical
   {
     id: 'socket_install',
     category: 'electrical',
     nameEn: 'Socket/Switch Installation',
     nameRu: 'Установка розетки/выключателя',
     descriptionEn: 'Install or replace electrical sockets and switches',
     descriptionRu: 'Установка или замена розеток и выключателей',
     icon: '🔌',
     basePrice: 500,
     currency: 'THB',
     estimatedTime: '30m',
     estimatedTimeEn: '30 minutes',
     estimatedTimeRu: '30 минут',
     includesEn: ['Old unit removal', 'New unit installation', 'Safety check'],
     includesRu: ['Демонтаж старого', 'Установка нового', 'Проверка безопасности'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'wiring_repair',
     category: 'electrical',
     nameEn: 'Wiring Repair',
     nameRu: 'Ремонт проводки',
     descriptionEn: 'Electrical wiring repair and short circuit fix',
     descriptionRu: 'Ремонт электропроводки и устранение замыканий',
     icon: '⚡',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '2-4h',
     estimatedTimeEn: '2-4 hours',
     estimatedTimeRu: '2-4 часа',
     includesEn: ['Fault detection', 'Wire replacement', 'Insulation', 'Testing'],
     includesRu: ['Поиск неисправности', 'Замена проводов', 'Изоляция', 'Проверка'],
     isUrgent: true,
     sortOrder: 2,
   },
   {
     id: 'chandelier_install',
     category: 'electrical',
     nameEn: 'Chandelier/Light Installation',
     nameRu: 'Установка люстры/светильника',
     descriptionEn: 'Professional lighting fixture installation',
     descriptionRu: 'Профессиональная установка осветительных приборов',
     icon: '💡',
     basePrice: 1000,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Mounting', 'Wiring connection', 'Testing'],
     includesRu: ['Монтаж', 'Подключение', 'Проверка работы'],
     sortOrder: 3,
   },
   {
     id: 'breaker_repair',
     category: 'electrical',
     nameEn: 'Circuit Breaker Repair',
     nameRu: 'Ремонт автоматов/щитка',
     descriptionEn: 'Circuit breaker panel repair and replacement',
     descriptionRu: 'Ремонт и замена автоматов в электрощитке',
     icon: '🔲',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Diagnostics', 'Breaker replacement', 'Panel inspection'],
     includesRu: ['Диагностика', 'Замена автоматов', 'Осмотр щитка'],
     isUrgent: true,
     sortOrder: 4,
   },
 
   // 🛠️ Handyman
   {
     id: 'furniture_assembly',
     category: 'handyman',
     nameEn: 'Furniture Assembly',
     nameRu: 'Сборка мебели',
     descriptionEn: 'Assembly of IKEA and other flat-pack furniture',
     descriptionRu: 'Сборка мебели IKEA и другой корпусной мебели',
     icon: '🪑',
     basePrice: 500,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Unpacking', 'Assembly', 'Installation'],
     includesRu: ['Распаковка', 'Сборка', 'Установка'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'door_repair',
     category: 'handyman',
     nameEn: 'Door Repair/Adjustment',
     nameRu: 'Ремонт/регулировка дверей',
     descriptionEn: 'Fix squeaky, stuck, or misaligned doors',
     descriptionRu: 'Устранение скрипа, заедания и перекоса дверей',
     icon: '🚪',
     basePrice: 800,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Hinge adjustment', 'Lubrication', 'Alignment'],
     includesRu: ['Регулировка петель', 'Смазка', 'Выравнивание'],
     sortOrder: 2,
   },
   {
     id: 'lock_change',
     category: 'handyman',
     nameEn: 'Lock Replacement',
     nameRu: 'Замена замков',
     descriptionEn: 'Replace door locks for improved security',
     descriptionRu: 'Замена дверных замков для безопасности',
     icon: '🔐',
     basePrice: 1200,
     currency: 'THB',
     estimatedTime: '30m-1h',
     estimatedTimeEn: '30 min - 1 hour',
     estimatedTimeRu: '30 мин - 1 час',
     includesEn: ['Old lock removal', 'New lock installation', 'Key testing'],
     includesRu: ['Демонтаж старого замка', 'Установка нового', 'Проверка ключей'],
     sortOrder: 3,
   },
   {
     id: 'tv_mounting',
     category: 'handyman',
     nameEn: 'TV Wall Mounting',
     nameRu: 'Монтаж ТВ на стену',
     descriptionEn: 'Securely mount your TV on the wall',
     descriptionRu: 'Надёжное крепление телевизора на стену',
     icon: '📺',
     basePrice: 800,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Bracket installation', 'TV mounting', 'Cable management'],
     includesRu: ['Установка кронштейна', 'Монтаж ТВ', 'Прокладка кабелей'],
     sortOrder: 4,
   },
   {
     id: 'curtain_install',
     category: 'handyman',
     nameEn: 'Curtain/Blinds Installation',
     nameRu: 'Установка штор/жалюзи',
     descriptionEn: 'Install curtain rods, blinds, or drapes',
     descriptionRu: 'Установка карнизов, жалюзи или штор',
     icon: '🪟',
     basePrice: 600,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Bracket mounting', 'Rod/track installation', 'Curtain hanging'],
     includesRu: ['Монтаж креплений', 'Установка карниза', 'Навешивание штор'],
     sortOrder: 5,
   },
   {
     id: 'shelf_install',
     category: 'handyman',
     nameEn: 'Shelf/Mirror Mounting',
     nameRu: 'Монтаж полок/зеркал',
     descriptionEn: 'Securely install shelves, mirrors, or artwork',
     descriptionRu: 'Надёжная установка полок, зеркал или картин',
     icon: '🖼️',
     basePrice: 500,
     currency: 'THB',
     estimatedTime: '30m-1h',
     estimatedTimeEn: '30 min - 1 hour',
     estimatedTimeRu: '30 мин - 1 час',
     includesEn: ['Wall marking', 'Drilling', 'Secure mounting'],
     includesRu: ['Разметка', 'Сверление', 'Надёжное крепление'],
     sortOrder: 6,
   },
 
   // 🔌 Appliance Repair
   {
     id: 'washing_machine',
     category: 'appliance_repair',
     nameEn: 'Washing Machine Repair',
     nameRu: 'Ремонт стиральной машины',
     descriptionEn: 'Diagnose and repair washing machine issues',
     descriptionRu: 'Диагностика и ремонт неисправностей стиральной машины',
     icon: '🧺',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Diagnostics', 'Repair', 'Testing'],
     includesRu: ['Диагностика', 'Ремонт', 'Проверка работы'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'fridge_repair',
     category: 'appliance_repair',
     nameEn: 'Refrigerator Repair',
     nameRu: 'Ремонт холодильника',
     descriptionEn: 'Fix cooling issues, leaks, and other fridge problems',
     descriptionRu: 'Устранение проблем с охлаждением, течей и других неисправностей',
     icon: '🧊',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '1-3h',
     estimatedTimeEn: '1-3 hours',
     estimatedTimeRu: '1-3 часа',
     includesEn: ['Diagnostics', 'Compressor check', 'Repair', 'Gas refill if needed'],
     includesRu: ['Диагностика', 'Проверка компрессора', 'Ремонт', 'Заправка при необходимости'],
     isUrgent: true,
     sortOrder: 2,
   },
   {
     id: 'oven_repair',
     category: 'appliance_repair',
     nameEn: 'Oven/Stove Repair',
     nameRu: 'Ремонт духовки/плиты',
     descriptionEn: 'Repair electric or gas oven and stove issues',
     descriptionRu: 'Ремонт электрических и газовых духовок и плит',
     icon: '🍳',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Diagnostics', 'Element replacement', 'Safety check'],
     includesRu: ['Диагностика', 'Замена элементов', 'Проверка безопасности'],
     sortOrder: 3,
   },
   {
     id: 'microwave_repair',
     category: 'appliance_repair',
     nameEn: 'Microwave Repair',
     nameRu: 'Ремонт микроволновки',
     descriptionEn: 'Fix microwave heating and door issues',
     descriptionRu: 'Ремонт нагрева и дверцы микроволновой печи',
     icon: '📡',
     basePrice: 1000,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Diagnostics', 'Repair', 'Testing'],
     includesRu: ['Диагностика', 'Ремонт', 'Проверка'],
     sortOrder: 4,
   },
 
   // 🧹 Cleaning
   {
     id: 'deep_cleaning',
     category: 'cleaning',
     nameEn: 'Deep Cleaning',
     nameRu: 'Генеральная уборка',
     descriptionEn: 'Thorough deep cleaning of entire home',
     descriptionRu: 'Тщательная генеральная уборка всего дома',
     icon: '✨',
     basePrice: 2500,
     currency: 'THB',
     estimatedTime: '4-6h',
     estimatedTimeEn: '4-6 hours',
     estimatedTimeRu: '4-6 часов',
     includesEn: ['All rooms', 'Kitchen deep clean', 'Bathroom sanitization', 'Floor washing'],
     includesRu: ['Все комнаты', 'Глубокая уборка кухни', 'Санитизация ванной', 'Мытьё полов'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'move_out_cleaning',
     category: 'cleaning',
     nameEn: 'Move-out Cleaning',
     nameRu: 'Уборка при выезде',
     descriptionEn: 'Professional cleaning before moving out',
     descriptionRu: 'Профессиональная уборка перед выездом из жилья',
     icon: '🏠',
     basePrice: 3000,
     currency: 'THB',
     estimatedTime: '5-8h',
     estimatedTimeEn: '5-8 hours',
     estimatedTimeRu: '5-8 часов',
     includesEn: ['Deep cleaning', 'Appliance cleaning', 'Window washing', 'Deposit-ready finish'],
     includesRu: ['Генеральная уборка', 'Чистка техники', 'Мытьё окон', 'Подготовка к сдаче'],
     sortOrder: 2,
   },
   {
     id: 'sofa_cleaning',
     category: 'cleaning',
     nameEn: 'Sofa/Upholstery Cleaning',
     nameRu: 'Химчистка мебели',
     descriptionEn: 'Professional upholstery and sofa cleaning',
     descriptionRu: 'Профессиональная химчистка мягкой мебели',
     icon: '🛋️',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '2-3h',
     estimatedTimeEn: '2-3 hours',
     estimatedTimeRu: '2-3 часа',
     includesEn: ['Stain removal', 'Deep cleaning', 'Deodorizing'],
     includesRu: ['Удаление пятен', 'Глубокая чистка', 'Устранение запахов'],
     sortOrder: 3,
   },
   {
     id: 'mattress_cleaning',
     category: 'cleaning',
     nameEn: 'Mattress Cleaning',
     nameRu: 'Чистка матраса',
     descriptionEn: 'Deep cleaning and sanitization of mattress',
     descriptionRu: 'Глубокая чистка и санитизация матраса',
     icon: '🛏️',
     basePrice: 1200,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Vacuum', 'Stain treatment', 'Sanitization', 'Deodorizing'],
     includesRu: ['Пылесос', 'Обработка пятен', 'Санитизация', 'Удаление запахов'],
     sortOrder: 4,
   },
 
   // 🏊 Pool & Jacuzzi
   {
     id: 'pool_cleaning',
     category: 'pool',
     nameEn: 'Pool Cleaning',
     nameRu: 'Чистка бассейна',
     descriptionEn: 'Complete pool cleaning and maintenance',
     descriptionRu: 'Полная чистка и обслуживание бассейна',
     icon: '🏊',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '2-3h',
     estimatedTimeEn: '2-3 hours',
     estimatedTimeRu: '2-3 часа',
     includesEn: ['Skimming', 'Vacuuming', 'Chemical balance', 'Filter check'],
     includesRu: ['Очистка поверхности', 'Пылесос дна', 'Баланс химии', 'Проверка фильтра'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'pool_repair',
     category: 'pool',
     nameEn: 'Pool Equipment Repair',
     nameRu: 'Ремонт оборудования бассейна',
     descriptionEn: 'Repair pumps, filters, and pool equipment',
     descriptionRu: 'Ремонт насосов, фильтров и оборудования бассейна',
     icon: '🔧',
     basePrice: 2500,
     currency: 'THB',
     estimatedTime: '2-4h',
     estimatedTimeEn: '2-4 hours',
     estimatedTimeRu: '2-4 часа',
     includesEn: ['Diagnostics', 'Pump repair', 'Filter service', 'Testing'],
     includesRu: ['Диагностика', 'Ремонт насоса', 'Обслуживание фильтра', 'Проверка'],
     sortOrder: 2,
   },
   {
     id: 'jacuzzi_service',
     category: 'pool',
     nameEn: 'Jacuzzi Service',
     nameRu: 'Обслуживание джакузи',
     descriptionEn: 'Jacuzzi cleaning, maintenance, and repair',
     descriptionRu: 'Чистка, обслуживание и ремонт джакузи',
     icon: '🛁',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '2h',
     estimatedTimeEn: '2 hours',
     estimatedTimeRu: '2 часа',
     includesEn: ['Cleaning', 'Jet check', 'Water treatment', 'Pump inspection'],
     includesRu: ['Чистка', 'Проверка форсунок', 'Обработка воды', 'Осмотр насоса'],
     sortOrder: 3,
   },
 
   // 🌿 Garden
   {
     id: 'lawn_mowing',
     category: 'garden',
     nameEn: 'Lawn Mowing',
     nameRu: 'Стрижка газона',
     descriptionEn: 'Professional lawn mowing and trimming',
     descriptionRu: 'Профессиональная стрижка газона и обрезка',
     icon: '🌱',
     basePrice: 800,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Mowing', 'Edge trimming', 'Debris cleanup'],
     includesRu: ['Стрижка', 'Обрезка краёв', 'Уборка мусора'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'tree_pruning',
     category: 'garden',
     nameEn: 'Tree/Bush Pruning',
     nameRu: 'Обрезка деревьев/кустов',
     descriptionEn: 'Professional tree and bush trimming',
     descriptionRu: 'Профессиональная обрезка деревьев и кустарников',
     icon: '🌳',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '2-4h',
     estimatedTimeEn: '2-4 hours',
     estimatedTimeRu: '2-4 часа',
     includesEn: ['Pruning', 'Shaping', 'Debris removal'],
     includesRu: ['Обрезка', 'Формирование', 'Вывоз отходов'],
     sortOrder: 2,
   },
   {
     id: 'garden_cleanup',
     category: 'garden',
     nameEn: 'Garden Cleanup',
     nameRu: 'Уборка участка',
     descriptionEn: 'Complete garden cleanup and maintenance',
     descriptionRu: 'Полная уборка и приведение участка в порядок',
     icon: '🧹',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '3-5h',
     estimatedTimeEn: '3-5 hours',
     estimatedTimeRu: '3-5 часов',
     includesEn: ['Weeding', 'Leaf removal', 'Debris cleanup', 'General tidy-up'],
     includesRu: ['Прополка', 'Уборка листвы', 'Вывоз мусора', 'Общая уборка'],
     sortOrder: 3,
   },
 
   // 🐜 Pest Control
   {
     id: 'pest_general',
     category: 'pest_control',
     nameEn: 'General Pest Control',
     nameRu: 'Общая дезинсекция',
     descriptionEn: 'Treatment for ants, cockroaches, and common pests',
     descriptionRu: 'Обработка от муравьёв, тараканов и других насекомых',
     icon: '🐜',
     basePrice: 2000,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Inspection', 'Treatment', 'Prevention advice'],
     includesRu: ['Осмотр', 'Обработка', 'Рекомендации по профилактике'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'termite_control',
     category: 'pest_control',
     nameEn: 'Termite Treatment',
     nameRu: 'Обработка от термитов',
     descriptionEn: 'Professional termite inspection and treatment',
     descriptionRu: 'Профессиональная обработка против термитов',
     icon: '🪲',
     basePrice: 5000,
     currency: 'THB',
     estimatedTime: '3-4h',
     estimatedTimeEn: '3-4 hours',
     estimatedTimeRu: '3-4 часа',
     includesEn: ['Full inspection', 'Treatment', 'Barrier installation', 'Follow-up'],
     includesRu: ['Полный осмотр', 'Обработка', 'Установка барьера', 'Повторный контроль'],
     sortOrder: 2,
   },
   {
     id: 'mosquito_control',
     category: 'pest_control',
     nameEn: 'Mosquito Control',
     nameRu: 'Обработка от комаров',
     descriptionEn: 'Mosquito fogging and prevention treatment',
     descriptionRu: 'Фумигация и профилактическая обработка от комаров',
     icon: '🦟',
     basePrice: 1500,
     currency: 'THB',
     estimatedTime: '1h',
     estimatedTimeEn: '1 hour',
     estimatedTimeRu: '1 час',
     includesEn: ['Fogging', 'Breeding spot treatment', 'Prevention advice'],
     includesRu: ['Фумигация', 'Обработка мест размножения', 'Рекомендации'],
     sortOrder: 3,
   },
 
   // 🔒 Security
   {
     id: 'cctv_install',
     category: 'security',
     nameEn: 'CCTV Installation',
     nameRu: 'Установка видеонаблюдения',
     descriptionEn: 'Security camera system installation',
     descriptionRu: 'Установка системы видеонаблюдения',
     icon: '📹',
     basePrice: 5000,
     currency: 'THB',
     estimatedTime: '4-6h',
     estimatedTimeEn: '4-6 hours',
     estimatedTimeRu: '4-6 часов',
     includesEn: ['Camera mounting', 'DVR setup', 'Mobile app config', 'Testing'],
     includesRu: ['Монтаж камер', 'Настройка DVR', 'Настройка приложения', 'Проверка'],
     sortOrder: 1,
   },
   {
     id: 'alarm_install',
     category: 'security',
     nameEn: 'Alarm System Installation',
     nameRu: 'Установка сигнализации',
     descriptionEn: 'Home alarm and security system setup',
     descriptionRu: 'Установка домашней сигнализации',
     icon: '🚨',
     basePrice: 3000,
     currency: 'THB',
     estimatedTime: '2-3h',
     estimatedTimeEn: '2-3 hours',
     estimatedTimeRu: '2-3 часа',
     includesEn: ['Sensor installation', 'Control panel setup', 'Testing'],
     includesRu: ['Установка датчиков', 'Настройка панели', 'Проверка'],
     sortOrder: 2,
   },
 
   // 📦 Moving
   {
     id: 'local_moving',
     category: 'moving',
     nameEn: 'Local Moving',
     nameRu: 'Местный переезд',
     descriptionEn: 'Professional moving service within the city',
     descriptionRu: 'Профессиональный переезд в пределах города',
     icon: '🚚',
     basePrice: 3000,
     currency: 'THB',
     estimatedTime: '4-8h',
     estimatedTimeEn: '4-8 hours',
     estimatedTimeRu: '4-8 часов',
     includesEn: ['Packing assistance', 'Loading', 'Transport', 'Unloading'],
     includesRu: ['Помощь с упаковкой', 'Погрузка', 'Перевозка', 'Разгрузка'],
     isPopular: true,
     sortOrder: 1,
   },
   {
     id: 'furniture_moving',
     category: 'moving',
     nameEn: 'Furniture Moving',
     nameRu: 'Перемещение мебели',
     descriptionEn: 'Move heavy furniture within home or between rooms',
     descriptionRu: 'Перемещение тяжёлой мебели внутри дома',
     icon: '🛋️',
     basePrice: 1000,
     currency: 'THB',
     estimatedTime: '1-2h',
     estimatedTimeEn: '1-2 hours',
     estimatedTimeRu: '1-2 часа',
     includesEn: ['Disassembly if needed', 'Moving', 'Reassembly'],
     includesRu: ['Разборка при необходимости', 'Перемещение', 'Сборка'],
     sortOrder: 2,
   },
 ];
 
 // Helper functions
 export function getServiceFunctionById(id: string): ServiceFunction | undefined {
   return HOME_SERVICE_FUNCTIONS.find(f => f.id === id);
 }
 
 export function getServiceFunctionsByCategory(category: ServiceCategory): ServiceFunction[] {
   return HOME_SERVICE_FUNCTIONS.filter(f => f.category === category).sort((a, b) => a.sortOrder - b.sortOrder);
 }
 
 export function getPopularServiceFunctions(): ServiceFunction[] {
   return HOME_SERVICE_FUNCTIONS.filter(f => f.isPopular).sort((a, b) => a.sortOrder - b.sortOrder);
 }
 
 export function getUrgentServiceFunctions(): ServiceFunction[] {
   return HOME_SERVICE_FUNCTIONS.filter(f => f.isUrgent);
 }
 
 export function getCategoryById(id: ServiceCategory): ServiceCategoryConfig | undefined {
   return SERVICE_CATEGORIES.find(c => c.id === id);
 }
 
 export function searchServiceFunctions(query: string, language: 'en' | 'ru' = 'en'): ServiceFunction[] {
   const lowerQuery = query.toLowerCase();
   return HOME_SERVICE_FUNCTIONS.filter(f => {
     const name = language === 'ru' ? f.nameRu : f.nameEn;
     const description = language === 'ru' ? f.descriptionRu : f.descriptionEn;
     return name.toLowerCase().includes(lowerQuery) || description.toLowerCase().includes(lowerQuery);
   });
 }