/**
 * Phuket Areas — Static data for area guides
 * Investment-focused profiles of Phuket districts
 */

export interface PhuketArea {
  slug: string;
  name_en: string;
  name_ru: string;
  description_en: string;
  description_ru: string;
  lat: number;
  lng: number;
  avg_price_sqm: number;
  avg_yield: number;
  investment_rating: number; // 1-5
  highlights_en: string[];
  highlights_ru: string[];
  pros_en: string[];
  pros_ru: string[];
  cons_en: string[];
  cons_ru: string[];
  distance_airport_km: number;
  distance_beach_km: number;
  popular_for: string[];
}

export const PHUKET_AREAS: PhuketArea[] = [
  {
    slug: 'bang-tao',
    name_en: 'Bang Tao',
    name_ru: 'Банг Тао',
    description_en: 'Premium beachfront area home to Laguna Phuket complex. One of the longest beaches on the island with upscale resorts, international restaurants, and world-class golf courses.',
    description_ru: 'Премиальный район на побережье, где расположен комплекс Laguna Phuket. Один из самых длинных пляжей острова с элитными курортами, международными ресторанами и гольф-клубами мирового класса.',
    lat: 7.9821, lng: 98.2901,
    avg_price_sqm: 120000,
    avg_yield: 6.5,
    investment_rating: 5,
    highlights_en: ['Laguna Phuket resort complex', '6km beach', 'Boat Avenue shopping', 'International schools nearby'],
    highlights_ru: ['Курортный комплекс Laguna Phuket', 'Пляж 6 км', 'Торговый район Boat Avenue', 'Международные школы рядом'],
    pros_en: ['Highest capital appreciation', 'Strong rental demand', 'Premium infrastructure', 'Beach access'],
    pros_ru: ['Максимальный рост капитала', 'Высокий спрос на аренду', 'Премиальная инфраструктура', 'Доступ к пляжу'],
    cons_en: ['Higher entry price', 'Busy in high season', 'Traffic congestion'],
    cons_ru: ['Высокий порог входа', 'Людно в высокий сезон', 'Пробки'],
    distance_airport_km: 22,
    distance_beach_km: 0.5,
    popular_for: ['luxury', 'family', 'golf', 'expat'],
  },
  {
    slug: 'laguna',
    name_en: 'Laguna',
    name_ru: 'Лагуна',
    description_en: 'Integrated resort community within Bang Tao area. Self-contained lifestyle with hotels, golf, shopping, and dining all within walking distance.',
    description_ru: 'Интегрированный курортный комплекс в районе Банг Тао. Самодостаточный стиль жизни с отелями, гольфом, магазинами и ресторанами в пешей доступности.',
    lat: 7.9850, lng: 98.2920,
    avg_price_sqm: 130000,
    avg_yield: 6.0,
    investment_rating: 5,
    highlights_en: ['5 resort hotels', 'Laguna Golf Course', 'Canal Village', 'Private beach'],
    highlights_ru: ['5 курортных отелей', 'Laguna Golf Course', 'Canal Village', 'Частный пляж'],
    pros_en: ['Established brand', 'Consistent rental income', 'Resort management', 'Secure community'],
    pros_ru: ['Сложившийся бренд', 'Стабильный арендный доход', 'Курортное управление', 'Закрытая территория'],
    cons_en: ['Very high prices', 'Resort fees', 'Can feel enclosed'],
    cons_ru: ['Очень высокие цены', 'Курортные сборы', 'Может ощущаться изолированность'],
    distance_airport_km: 20,
    distance_beach_km: 0.3,
    popular_for: ['luxury', 'golf', 'resort'],
  },
  {
    slug: 'kamala',
    name_en: 'Kamala',
    name_ru: 'Камала',
    description_en: 'Charming beach town between Patong and Surin. Quieter atmosphere with village feel, excellent beach, and growing upscale development scene.',
    description_ru: 'Очаровательный пляжный городок между Патонгом и Сурином. Спокойная атмосфера с ощущением деревни, отличный пляж и растущий сегмент премиальной застройки.',
    lat: 7.9552, lng: 98.2810,
    avg_price_sqm: 95000,
    avg_yield: 7.0,
    investment_rating: 4,
    highlights_en: ['Beautiful beach', 'Cafe Phuket scene', 'Hillside villas', 'Close to Patong'],
    highlights_ru: ['Красивый пляж', 'Кафе Пхукета', 'Виллы на холмах', 'Близко к Патонгу'],
    pros_en: ['Good value for money', 'Growing area', 'Quiet but accessible', 'Strong appreciation potential'],
    pros_ru: ['Хорошее соотношение цена/качество', 'Развивающийся район', 'Тихо, но доступно', 'Высокий потенциал роста'],
    cons_en: ['Limited nightlife', 'Hilly terrain', 'Fewer amenities than Bang Tao'],
    cons_ru: ['Мало ночной жизни', 'Холмистая местность', 'Меньше инфраструктуры чем в Банг Тао'],
    distance_airport_km: 26,
    distance_beach_km: 0.3,
    popular_for: ['family', 'quiet', 'value'],
  },
  {
    slug: 'surin',
    name_en: 'Surin',
    name_ru: 'Сурин',
    description_en: 'Exclusive millionaire\'s row with stunning sunset views. Known for luxury villas, beach clubs, and some of the most expensive real estate on the island.',
    description_ru: 'Эксклюзивный район миллионеров с потрясающими закатами. Известен роскошными виллами, пляжными клубами и одной из самых дорогих недвижимостей на острове.',
    lat: 7.9712, lng: 98.2780,
    avg_price_sqm: 140000,
    avg_yield: 5.5,
    investment_rating: 4,
    highlights_en: ['Luxury villas', 'Sunset views', 'Beach clubs', 'Twin Palms resort'],
    highlights_ru: ['Люксовые виллы', 'Виды на закат', 'Пляжные клубы', 'Курорт Twin Palms'],
    pros_en: ['Ultra-premium location', 'Exclusive community', 'Sunset views', 'Status address'],
    pros_ru: ['Ультрапремиальная локация', 'Эксклюзивное сообщество', 'Виды на закат', 'Статусный адрес'],
    cons_en: ['Very expensive', 'Limited parking', 'Small beach', 'Low rental volume'],
    cons_ru: ['Очень дорого', 'Мало парковок', 'Маленький пляж', 'Низкий объём аренды'],
    distance_airport_km: 24,
    distance_beach_km: 0.2,
    popular_for: ['luxury', 'villa', 'sunset'],
  },
  {
    slug: 'layan',
    name_en: 'Layan',
    name_ru: 'Лаян',
    description_en: 'Emerging premium area north of Bang Tao. Quieter, more natural setting with new luxury developments. National park proximity adds green value.',
    description_ru: 'Развивающийся премиальный район к северу от Банг Тао. Тихая, более естественная среда с новыми элитными проектами. Близость к национальному парку добавляет зелёную ценность.',
    lat: 8.0050, lng: 98.2950,
    avg_price_sqm: 100000,
    avg_yield: 6.0,
    investment_rating: 4,
    highlights_en: ['Sirinat National Park', 'Quiet beaches', 'New developments', 'Nature setting'],
    highlights_ru: ['Нац. парк Сиринат', 'Тихие пляжи', 'Новые проекты', 'Природная среда'],
    pros_en: ['Lower prices than Bang Tao', 'Nature proximity', 'Development potential', 'Privacy'],
    pros_ru: ['Цены ниже чем в Банг Тао', 'Близость к природе', 'Потенциал развития', 'Приватность'],
    cons_en: ['Less developed', 'Further from amenities', 'National park restrictions'],
    cons_ru: ['Менее развит', 'Далеко от инфраструктуры', 'Ограничения нац. парка'],
    distance_airport_km: 15,
    distance_beach_km: 0.5,
    popular_for: ['nature', 'quiet', 'emerging'],
  },
  {
    slug: 'nai-harn',
    name_en: 'Nai Harn',
    name_ru: 'Най Харн',
    description_en: 'Beautiful southern beach with local Thai community feel. Popular with long-term expats. More affordable than west coast premium areas.',
    description_ru: 'Красивый южный пляж с атмосферой тайской общины. Популярен среди экспатов на ПМЖ. Более доступный чем премиальные районы западного побережья.',
    lat: 7.7720, lng: 98.3050,
    avg_price_sqm: 75000,
    avg_yield: 7.5,
    investment_rating: 4,
    highlights_en: ['Pristine beach', 'Local restaurants', 'Windmill viewpoint', 'Expat community'],
    highlights_ru: ['Чистый пляж', 'Местные рестораны', 'Смотровая Windmill', 'Сообщество экспатов'],
    pros_en: ['Strong yield/price ratio (~7.5%)', 'Beautiful scenery', 'Authentic feel', 'Growing expat market'],
    pros_ru: ['Высокая доходность/цена (~7,5%)', 'Красивые виды', 'Аутентичная атмосфера', 'Растущий рынок экспатов'],
    cons_en: ['Far from airport', 'Limited shopping', 'Seasonal beach'],
    cons_ru: ['Далеко от аэропорта', 'Мало магазинов', 'Сезонный пляж'],
    distance_airport_km: 45,
    distance_beach_km: 0.3,
    popular_for: ['expat', 'value', 'beach'],
  },
  {
    slug: 'rawai',
    name_en: 'Rawai',
    name_ru: 'Равай',
    description_en: 'Southern tip of Phuket, popular residential area for expats. Known for seafood markets, proximity to islands, and relaxed lifestyle. Great value.',
    description_ru: 'Южная оконечность Пхукета, популярный жилой район для экспатов. Известен рыбными рынками, близостью к островам и расслабленным стилем жизни. Отличная цена.',
    lat: 7.7650, lng: 98.3350,
    avg_price_sqm: 65000,
    avg_yield: 7.0,
    investment_rating: 3,
    highlights_en: ['Seafood markets', 'Island hopping', 'Muay Thai gyms', 'Expat hub'],
    highlights_ru: ['Рыбные рынки', 'Поездки на острова', 'Тренажёрные залы муай-тай', 'Центр экспатов'],
    pros_en: ['Most affordable south', 'Strong expat demand', 'Year-round living', 'Island access'],
    pros_ru: ['Самый доступный на юге', 'Высокий спрос экспатов', 'Жизнь круглый год', 'Доступ к островам'],
    cons_en: ['No swimming beach', 'Away from tourist hubs', 'Less capital growth'],
    cons_ru: ['Нет купального пляжа', 'Далеко от туристических зон', 'Меньший рост капитала'],
    distance_airport_km: 48,
    distance_beach_km: 2,
    popular_for: ['expat', 'value', 'local'],
  },
  {
    slug: 'cherngtalay',
    name_en: 'Cherngtalay',
    name_ru: 'Чернгталай',
    description_en: 'Fast-developing area inland from Bang Tao. Home to Porto de Phuket, Blue Tree, international schools. Excellent value with Bang Tao proximity.',
    description_ru: 'Быстро развивающийся район в глубине от Банг Тао. Здесь расположены Porto de Phuket, Blue Tree, международные школы. Отличная цена с близостью к Банг Тао.',
    lat: 7.9900, lng: 98.3100,
    avg_price_sqm: 80000,
    avg_yield: 7.0,
    investment_rating: 4,
    highlights_en: ['Blue Tree water park', 'Porto de Phuket', 'UWC school', 'New malls'],
    highlights_ru: ['Аквапарк Blue Tree', 'Porto de Phuket', 'Школа UWC', 'Новые торговые центры'],
    pros_en: ['Bang Tao access at lower price', 'International schools', 'Growing fast', 'Family-friendly'],
    pros_ru: ['Доступ к Банг Тао по низкой цене', 'Международные школы', 'Быстрый рост', 'Подходит для семей'],
    cons_en: ['Inland (no beach)', 'Construction everywhere', 'Not walkable'],
    cons_ru: ['Нет пляжа', 'Стройки повсюду', 'Не пешеходный'],
    distance_airport_km: 18,
    distance_beach_km: 3,
    popular_for: ['family', 'value', 'school'],
  },
  {
    slug: 'kata',
    name_en: 'Kata',
    name_ru: 'Ката',
    description_en: 'Popular tourist beach on the west coast. Vibrant mix of hotels, shops, and restaurants. Good rental yields from tourism traffic.',
    description_ru: 'Популярный туристический пляж на западном побережье. Оживлённая смесь отелей, магазинов и ресторанов. Хорошая доходность от туристического потока.',
    lat: 7.8200, lng: 98.2980,
    avg_price_sqm: 70000,
    avg_yield: 7.5,
    investment_rating: 3,
    highlights_en: ['Two beaches', 'Kata viewpoint', 'Surf season', 'Tourist infrastructure'],
    highlights_ru: ['Два пляжа', 'Смотровая Ката', 'Сезон сёрфинга', 'Туристическая инфраструктура'],
    pros_en: ['High tourist demand', 'Good rental yields', 'Affordable entry', 'Beach access'],
    pros_ru: ['Высокий туристический спрос', 'Хорошая доходность', 'Доступный вход', 'Доступ к пляжу'],
    cons_en: ['Very touristy', 'Seasonal', 'Older developments', 'Traffic'],
    cons_ru: ['Очень туристический', 'Сезонность', 'Старая застройка', 'Пробки'],
    distance_airport_km: 40,
    distance_beach_km: 0.3,
    popular_for: ['tourism', 'rental', 'surf'],
  },
  {
    slug: 'phuket-town',
    name_en: 'Phuket Town',
    name_ru: 'Пхукет Таун',
    description_en: 'The cultural heart of Phuket. Sino-Portuguese architecture, local markets, art galleries, and a developed food scene.',
    description_ru: 'Культурное сердце Пхукета. Китайско-португальская архитектура, местные рынки, арт-галереи и развитая гастрономическая сцена.',
    lat: 7.8847, lng: 98.3881,
    avg_price_sqm: 55000,
    avg_yield: 6.0,
    investment_rating: 3,
    highlights_en: ['Old Town heritage', 'Weekend markets', 'Hospitals nearby', 'Government offices'],
    highlights_ru: ['Историческая часть города', 'Выходные рынки', 'Больницы рядом', 'Госучреждения'],
    pros_en: ['Lowest prices', 'Cultural value', 'Year-round demand', 'Central location'],
    pros_ru: ['Самые низкие цены', 'Культурная ценность', 'Круглогодичный спрос', 'Центральное расположение'],
    cons_en: ['No beach', 'Less tourist appeal', 'Urban setting', 'Older buildings'],
    cons_ru: ['Нет пляжа', 'Меньше интереса туристов', 'Городская среда', 'Старые здания'],
    distance_airport_km: 32,
    distance_beach_km: 10,
    popular_for: ['culture', 'budget', 'local'],
  },
  {
    slug: 'patong',
    name_en: 'Patong',
    name_ru: 'Патонг',
    description_en: 'The entertainment capital of Phuket. 3km curved beach with the densest tourism infrastructure on the island — hotels, nightlife, shopping, watersports. Highest rental velocity, weakest capital appreciation.',
    description_ru: 'Развлекательная столица Пхукета. 3-километровый пляж с самой плотной туристической инфраструктурой острова — отели, ночная жизнь, шоппинг, водные виды спорта. Самая высокая скорость аренды, слабый рост капитала.',
    lat: 7.8967, lng: 98.2960,
    avg_price_sqm: 75000,
    avg_yield: 8.0,
    investment_rating: 3,
    highlights_en: ['Bangla Road nightlife', 'Jungceylon mall', '3km beach', 'Best ADR in low season'],
    highlights_ru: ['Ночная жизнь Bangla Road', 'ТЦ Jungceylon', 'Пляж 3 км', 'Лучший ADR в низкий сезон'],
    pros_en: ['Highest rental yields (~8%)', 'Year-round tourist demand', 'Lowest entry for beach access', 'Mature short-let market'],
    pros_ru: ['Максимальная доходность (~8%)', 'Туристический спрос круглый год', 'Самый низкий порог для пляжа', 'Зрелый рынок краткосрочной аренды'],
    cons_en: ['Noise and crowds', 'Slow capital appreciation', 'Image stigma for HNW buyers', 'Heavy traffic'],
    cons_ru: ['Шум и толпы', 'Медленный рост капитала', 'Имиджевый минус для HNW', 'Сильные пробки'],
    distance_airport_km: 35,
    distance_beach_km: 0.3,
    popular_for: ['tourism', 'rental', 'nightlife'],
  },
  {
    slug: 'karon',
    name_en: 'Karon',
    name_ru: 'Карон',
    description_en: 'Second-longest beach in Phuket, family-oriented neighbour of Patong. Calmer atmosphere with strong hotel base, growing condo supply, and reliable seasonal yields.',
    description_ru: 'Второй по длине пляж Пхукета, семейный сосед Патонга. Спокойная атмосфера, сильная отельная база, растущее предложение кондо и стабильная сезонная доходность.',
    lat: 7.8456, lng: 98.2950,
    avg_price_sqm: 70000,
    avg_yield: 7.5,
    investment_rating: 3,
    highlights_en: ['Karon beach (3km)', 'Family hotels', 'Viewpoint to Kata', 'Quieter than Patong'],
    highlights_ru: ['Пляж Карон (3 км)', 'Семейные отели', 'Смотровая на Кату', 'Спокойнее Патонга'],
    pros_en: ['Family-friendly demand', 'Solid seasonal yields', 'Affordable beachfront', 'Walking distance to Kata'],
    pros_ru: ['Семейный спрос', 'Стабильная сезонная доходность', 'Доступный фронт пляжа', 'Пешком до Каты'],
    cons_en: ['Strong seasonality', 'Limited nightlife', 'Older hotel stock', 'Far from airport'],
    cons_ru: ['Сильная сезонность', 'Мало ночной жизни', 'Старый отельный фонд', 'Далеко от аэропорта'],
    distance_airport_km: 38,
    distance_beach_km: 0.3,
    popular_for: ['family', 'tourism', 'rental'],
  },
  {
    slug: 'chalong',
    name_en: 'Chalong',
    name_ru: 'Чалонг',
    description_en: 'Southern bay area, gateway to island-hopping piers and expat services. Residential focus with marina, international schools, and value pricing. Not a beach area — utility location.',
    description_ru: 'Южный залив, ворота к причалам для поездок на острова и экспат-сервисам. Жилой район с мариной, международными школами и доступными ценами. Не пляжная зона — утилитарная локация.',
    lat: 7.8430, lng: 98.3380,
    avg_price_sqm: 60000,
    avg_yield: 6.5,
    investment_rating: 3,
    highlights_en: ['Chalong Pier', 'Marina', 'International schools', 'Big Buddha nearby'],
    highlights_ru: ['Пирс Чалонг', 'Марина', 'Международные школы', 'Большой Будда рядом'],
    pros_en: ['Lowest south-west prices', 'School proximity for families', 'Expat services hub', 'Year-round residency'],
    pros_ru: ['Самые низкие цены юго-запада', 'Близость к школам для семей', 'Хаб экспат-сервисов', 'Жильё круглый год'],
    cons_en: ['No swimmable beach', 'Industrial feel near pier', 'Lower tourist demand', 'Limited capital growth'],
    cons_ru: ['Нет купального пляжа', 'Промышленный вид у пирса', 'Низкий туристический спрос', 'Слабый рост капитала'],
    distance_airport_km: 42,
    distance_beach_km: 4,
    popular_for: ['family', 'expat', 'school', 'value'],
  },
];

export function getAreaBySlug(slug: string): PhuketArea | undefined {
  return PHUKET_AREAS.find(a => a.slug === slug);
}
